https://jira.croc.ru/browse/C2DEVEL-13094
C2Devel/terraform-provider-croccloud pull request #12
Opened 2023-03-06 14:19 UTC by DiGa66

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

2023-03-13 12:02 UTC, PixarV requested changes
Перед мерджем реквеста потребуется удалить ресурс и датасорс `aws_ami` из коммитов. Переформатирование документации будет выпускать позже по разделам.

2023-03-13 12:02 UTC, PixarV commented on website/docs/d/ami.html.markdown
>  ## Attributes Reference
Тут единственное число

2023-03-13 12:02 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +* `owners` — List of image owners to limit search. At least 1 value must be specified.
Поменялся тип тире, возможно из-за копирования с доки. Предлагаю оставить прежний вариант, т.к. он проставляется при нажатии на `-` по дефолту

2023-03-13 12:02 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +* `state_reason` — Describes a state change. Fields are `UNSET` if not available.
Должно располагаться ниже чем `sriov_net_support`, если по алфавиту

2023-03-13 12:02 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +  * Usage: Unlike most object attributes, these are accessed directly (e.g., `ebs.volume_size` or `ebs["volume_size"]`) rather than accessed through the first element of a list (e.g., `ebs[0].volume_
Лишняя точка в конце. Может оформить это как Note?

2023-03-13 12:02 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +  * Required: No
Это можно убрать, `Optional` в исходной версии случайно залетело

2023-03-13 12:02 UTC, PixarV commented on website/docs/r/ami.html.markdown
> +  * Default value: `x86_64`.
Лишняя точка

2023-03-13 12:02 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +* `executable_users` — Limit search to project with *explicit* launch permission on the image.
Должно быть над `filter`

2023-03-13 12:02 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +<a id="device-mappings-block"></a>
Может использовать имя блока в качествe id?

2023-03-13 12:02 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +  This element has a nested structure. See [description below](#ebs-element).
Предлагаю использовать одно имя для структур `ebs` и `block_device_mappings`: либо блоки, либо элементы. И формат id в якорях сделать общим

2023-03-13 12:02 UTC, PixarV commented on website/docs/r/ami.html.markdown
> +* `hypervisor` — The hypervisor type of the image.
Должен быть выше чем `id`. Или можно `id` вынести выше всех как в datasource

2023-03-13 12:02 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +* `arn` — The ARN of the image.
Есть ли какие-нибудь правила для расшифровки аббревиатур?

2023-03-13 12:02 UTC, PixarV commented on website/docs/index.html.markdown
> +Examples of using CROC Cloud services with Terraform are shown in [CROC Cloud services tutorials][c2-tutorials].
Это скорее все-таки примеры, чем туториалы

2023-03-14 15:33 UTC, DiGa66 commented on website/docs/d/ami.html.markdown
> +* `owners` — List of image owners to limit search. At least 1 value must be specified.
По дефолту ставится дефис, а не тире. В markdown длинное тире намного длиннее, чем в sphinx. Если ставить короткое тире, то оно выглядит аккуратнее. В принципе автозаменой несложно поменять дефисы на тире.

2023-03-14 15:41 UTC, DiGa66 commented on website/docs/d/ami.html.markdown
> +  * Usage: Unlike most object attributes, these are accessed directly (e.g., `ebs.volume_size` or `ebs["volume_size"]`) rather than accessed through the first element of a list (e.g., `ebs[0].volume_
переделал

2023-03-14 15:43 UTC, DiGa66 commented on website/docs/r/ami.html.markdown
> +  * Default value: `x86_64`.
убрал в фиксапе

2023-03-14 15:58 UTC, DiGa66 commented on website/docs/r/ami.html.markdown
> +* `hypervisor` — The hypervisor type of the image.
там id вообще вынесено из списка. Если здесь его тоже выносить из списка, то и текст описания раздела придется менять

2023-03-14 16:02 UTC, DiGa66 commented on website/docs/d/ami.html.markdown
> +* `arn` — The ARN of the image.
расшифровываются в первом месте, где встречаются, но не в заголовке
оформление разное, я предпочитают формат: расшифровка (АБРЕВИАТУРА)
Дальше по тексту уже используется без расшифровки.

Но поскольку у нас здесь не плоский текст, и к тому же не факт, что читать будут последовательно, то либо оставить без расшифровки (как известную), либо расшифровывать во всех местах

2023-03-14 16:15 UTC, DiGa66 commented on website/docs/index.html.markdown
> +Examples of using CROC Cloud services with Terraform are shown in [CROC Cloud services tutorials][c2-tutorials].
взял описание, что это такое, с нашего github

2023-03-22 07:35 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +* `owners` — List of image owners to limit search. At least 1 value must be specified.
Под автозамену могут случайно попасть куски кода. К тому же в некоторых ос может быть неочевидно как набрать символ 'короткое тире' с клавиатуры, т.е. для замены его потребуется откуда-то скопировать и отслеживать на ревью, что тире нужного вида. Кажется, что это только усложнит написание документации

2023-03-22 07:48 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +<a id="device-mappings-block"></a>
Добавь, пожалуйста, информацию про формат id на страницу с описанием и замени id в примерах

2023-03-22 08:38 UTC, PixarV commented on website/docs/index.html.markdown
> +Examples of using CROC Cloud services with Terraform can be found in [reference test suite on github][c2-tutorials].
По текстам вокруг встречается написание GitHub

2023-03-22 08:51 UTC, PixarV commented on website/docs/r/ami.html.markdown
> +* `hypervisor` — The hypervisor type of the image.
Может тогда одинаково и там, и тут оформить? судя по соседям - чаще встречается вариант с id в общем списке

2023-03-22 09:10 UTC, PixarV commented on website/docs/d/ami.html.markdown
> +* `arn` — The ARN of the image.
Можно догворится о том, что оставляем без расшифровки: например, ARN, EBS, которые оочень часто встречаются.

2023-03-28 15:55 UTC, DiGa66 commented on website/docs/r/ami.html.markdown
> +* `hypervisor` — The hypervisor type of the image.
включил в список

2023-03-28 15:56 UTC, DiGa66 commented on website/docs/d/ami.html.markdown
> +* `owners` — List of image owners to limit search. At least 1 value must be specified.
вернул дефисы

2023-03-29 07:04 UTC, PixarV approved these changes

2023-04-06 13:59 UTC, closed without merging