R53 zone+record suppport
C2Devel/terraform-provider-croccloud pull request #17
Opened 2023-06-02 11:10 UTC by cactusFriday

2023-06-05 14:14 UTC, PixarV requested changes
Нужно проверить прохождение юнит тестов и актуализировать документацию для реестра провайдеров.

2023-06-06 12:36 UTC, cactusFriday commented
> Нужно проверить прохождение юнит тестов и актуализировать документацию для реестра провайдеров.

Актуализировал доку
Юниты прошли
```
-> % make test
==> Checking that code complies with gofmt requirements...
go test ./...  -timeout=5m
?   	github.com/hashicorp/terraform-provider-aws	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/attrmap	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/experimental/sync	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/generate/allowsubcats	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/generate/checknames	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/generate/customends	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/generate/issuelabels	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/acctest	5.932s
ok  	github.com/hashicorp/terraform-provider-aws/internal/conns	(cached)
ok  	github.com/hashicorp/terraform-provider-aws/internal/create	(cached)
ok  	github.com/hashicorp/terraform-provider-aws/internal/experimental/nullable	(cached)
ok  	github.com/hashicorp/terraform-provider-aws/internal/flex	(cached)
?   	github.com/hashicorp/terraform-provider-aws/internal/generate/prlabels	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/generate/servicelabels	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/generate/sweepimp	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/generate/namevaluesfilters	5.885s
ok  	github.com/hashicorp/terraform-provider-aws/internal/provider	(cached)
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/accessanalyzer	7.410s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/account	13.468s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/acm	23.848s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/acmpca	23.102s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/amp	10.729s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/amplify	14.935s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigateway	20.695s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigatewayv2	12.859s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	16.232s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appconfig	21.295s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appflow	17.844s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appintegrations	19.866s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appmesh	17.741s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apprunner	23.315s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appstream	21.269s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appsync	27.288s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/athena	26.781s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	18.886s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscalingplans	12.972s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/backup	19.510s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/batch	19.817s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/budgets	17.846s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ce	16.734s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/chime	18.313s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloud9	16.893s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudcontrol	15.921s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation	14.770s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront	17.895s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudhsmv2	15.386s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudsearch	16.064s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail	16.174s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatch	16.660s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codeartifact	16.763s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codebuild	17.554s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codecommit	17.802s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codepipeline	17.329s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codestarconnections	19.155s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codestarnotifications	20.170s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidentity	20.235s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp	20.458s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/configservice	14.525s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/connect	20.060s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cur	14.400s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dataexchange	20.521s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/datapipeline	20.391s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/datasync	20.224s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dax	20.421s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/deploy	19.670s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/detective	18.307s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/devicefarm	18.171s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	19.916s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dlm	20.667s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dms	21.113s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/docdb	21.136s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ds	21.246s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb	21.969s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	38.427s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecr	7.591s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecrpublic	17.323s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	20.516s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	20.182s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/eks	22.835s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	14.929s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticbeanstalk	7.877s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticsearch	18.775s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elastictranscoder	17.901s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elb	33.656s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elbv2	24.045s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/emr	8.545s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/emrcontainers	13.913s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/events	20.510s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	22.040s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fms	22.576s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	17.820s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/gamelift	16.199s
?   	github.com/hashicorp/terraform-provider-aws/interna [...]

2023-06-13 08:03 UTC, PixarV requested changes

2023-06-13 08:03 UTC, PixarV commented on internal/service/route53/record.go
> +	// // If health check id is present send that to AWS
Закомментировался комментарий

2023-06-13 08:03 UTC, PixarV commented on internal/service/route53/zone.go
> +		log.Printf("[WARN] AssociateVPCWithHostedZone Request is not supported by C2")
Есть ли возможность перенести лог в `hostedZoneVPCAssociate` и закомментировать только обращение к апи в нем? Так лог не нужно будет дублировать и комментариев поменьше

2023-06-13 08:03 UTC, PixarV commented on internal/service/route53/zone.go
> +		log.Printf("[WARN] AssociateVPCWithHostedZone Request is not supported by C2")
Можно ли перенести лог в `hostedZoneVPCAssociate`, добавить лог в `hostedZoneVPCDisassociate` и только в них вызовы апи закомментить?

2023-06-13 08:03 UTC, PixarV commented on internal/service/route53/zone.go
> +		log.Printf("[WARN] DisableDNSSECForHostedZone Request is not supported by C2")
Аналогично, может в функцию `disableDNSSECForZone` перенести? )

2023-06-13 08:03 UTC, PixarV commented on website/docs/d/route53_zone.html.markdown
> -* `linked_service_principal` - The service that created the Hosted Zone (e.g., `servicediscovery.amazonaws.com`).
Перенеси в неподдерживаемые аттрибуты, пожалуйста (это поле будет включено в дата сорс с пустым значением)

2023-06-13 08:03 UTC, PixarV commented on website/docs/r/route53_zone.html.markdown
> -* `delegation_set_id` - (Optional) The ID of the reusable delegation set whose NS records you want to assign to the hosted zone. Conflicts with `vpc` as delegation sets can only be used for public zo
Перенеси в неподдерживаемые аттрибуты, пожалуйста (без `(Optional)` и `Conflicts with...`)

2023-06-13 08:03 UTC, PixarV commented on website/docs/r/route53_zone.html.markdown
> +* `vpc_region` - (Optional) Region of the VPC to associate. Defaults to AWS provider region.
```
* `vpc`
    * `vpc_region` - Region of the VPC to associate. Always <value>.
```
Можно без optional + надо посмотреть какое у него значение будет по умолчанию проставляться

2023-06-13 08:03 UTC, PixarV commented on website/docs/r/route53_record.html.markdown
> +* `set_identifier` - Unique identifier to differentiate records with routing policies from one another.
Не хватает значений, которыми по дефолту эти поля заполняются

2023-06-13 08:03 UTC, PixarV commented on website/docs/r/route53_record.html.markdown
> +page_title: "AWS: aws_route53_record"
```suggestion
page_title: "CROC Cloud: aws_route53_record"
```
Аналогично для остальных страничек из доки

2023-06-13 08:03 UTC, PixarV commented on website/docs/r/route53_record.html.markdown
> +* `records` - A string list of records. To specify a single record value longer than 255 characters such as a TXT record for DKIM, add `\"\"` inside the Terraform configuration string (e.g., `"first2
`Optional` или `Required` ?

2023-06-13 08:03 UTC, PixarV commented on website/docs/r/route53_record.html.markdown
> +* `type` - (Required) The record type. Valid values are `A`, `AAAA`, `CAA`, `CNAME`, `MX`, `NS`, `PTR`, `SRV` and `TXT`.
В доке C2 нет значения `CAA`

2023-06-14 09:52 UTC, PixarV approved these changes

2023-07-06 10:15 UTC, merged