update docs: s3, fix links and typos
C2Devel/terraform-provider-croccloud pull request #26
Opened 2023-10-06 11:35 UTC by PixarV

2023-10-06 13:18 UTC, PixarV commented on website/docs/r/s3_bucket_acl.html.markdown
>  S3 bucket ACL can be imported in one of four ways.
```suggestion
S3 bucket ACL can be imported in one of two ways.
```

2023-10-06 14:09 UTC, No-Rib requested changes

2023-10-06 14:09 UTC, No-Rib commented on website/docs/r/s3_bucket_acl.html.markdown
> +* `uri` - (Optional) URI of the grantee group. Supported groups are `http://acs.amazonaws.com/groups/global/AllUsers` and `http://acs.amazonaws.com/groups/global/AuthenticatedUsers`. Used only when `
Тут aws должен был остаться?

2023-10-06 14:15 UTC, PixarV commented on website/docs/r/s3_bucket_acl.html.markdown
> +* `uri` - (Optional) URI of the grantee group. Supported groups are `http://acs.amazonaws.com/groups/global/AllUsers` and `http://acs.amazonaws.com/groups/global/AuthenticatedUsers`. Used only when `
Да, группы в таком виде в примерах присутствуют ([c2docs](https://docs.cloud.croc.ru/en/api/s3/acl.html#id4))

2023-10-10 15:54 UTC, No-Rib approved these changes

2023-11-13 12:00 UTC, merged