add paas service docs
C2Devel/terraform-provider-croccloud pull request #27
Opened 2023-10-24 06:55 UTC by PixarV

2023-10-24 10:57 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +# This vpc is used in all examples below
Переделать на ссылку на ресурсы из места использования (memcached, redis)

2023-10-24 15:38 UTC, DiGa66 requested changes

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +# This vpc is used in all examples below
VPC

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +    # options format example
а это закомментированный кусок нужен?
можно пояснение добавить?

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +### PostgreSQL Service With Arbitrator
with
https://erinwrightwriting.com/what-is-headline-style-capitalization/#:~:text=Headline%2Dstyle%20capitalization%2C%20also%20called,in%20most%20books%20and%20magazines.

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  # Use the prepared provider configuration to connect to CROC Cloud S3
prepared -> predefined
S3 storage

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `data_volume` - (Optional) The service data volume parameters. The structure of this block is [described below](#data_volume).
лучше единообразно (см. предыдущий аргумент)
The data volume parameters for the service.

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `delete_interfaces_on_destroy` - (Optional) Indicates whether to delete instance network interfaces on service destroy. Defaults to `false`.
destroy -- глагол
on destroy -> when the service is destroyed

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `high_availability` - (Optional) Indicates whether to create a high availability cluster. Defaults to `false`.
мы в доке и вебке поменяли кластер на сервис
high availability service

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `name` - (Required) The service name. Value must start and end with Latin letters or number and
The value must start and end with a Latin letter or number ...

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `root_volume` - (Required) The service root volume parameters. The structure of this block is [described below](#root_volume).
... for the service

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +One of the following blocks with service parameters should be specified:
лучше must

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `bucket_name` - (Optional) The name of the bucket in object storage where the service backup will be saved.
is saved (лучше настоящее, если речь о регулярном действии)

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Parameter should be set if `enabled` is `true`.
The parameter must be set ...

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Parameter should be set if `enabled` is `true`.
must

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Parameter should be set if `enabled` is `true`.
The parameter must be ..

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `iops` - (Optional) The number of read/write operations per second for data volume. Parameter should be set if `type` is `io2`.
The parameter must be ...

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `iops` - (Optional) The number of read/write operations per second for root volume. Parameter should be set if `type` is `io2`.
The parameter must be ...

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `notification_email` - (Optional) The email address to which a notification that backup was created will be sent.
is sent

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `size` - (Optional) The size in GiB of the data volume. Defaults to `32`.
The size of the data volume in GiB.

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `size` - (Optional) The size in GiB of the root volume. Defaults to `32`.
The size of the root volume in GiB.

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +the `elasticsearch` block has the following structure:
кажется не совсем корректно: аргументы и структура разного уровня понятия:
... can contain the following arguments:

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `kibana` - (Optional) Indicates whether Kibana deploy is enabled. Defaults to `false`.
deployment

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `monitoring` - (Optional) Indicates whether a monitoring agent is enabled. Defaults to `false`.
наверно the -- это же конкретный агент

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `options` - (Optional) Map with other Elasticsearch parameters.
не очень понимаю, что здесь имелось ввиду,
но map обычно употребляется с to

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +If you need to use such parameter, contact [technical support].
such a parameter

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Value should be 8 to 128 characters and should not contain `-`, `!`, `:`, `;`, `%`, `'`, `"`,  `` ` `` and `\`.
The value must be 8 to 128 characters long and must not contain

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +## Memcached Arguments Reference
Argument

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +## PostgreSQL Arguments Reference
Argument

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +## Redis Arguments Reference
Argument

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +the `memcached` block has the following structure:
... can contain the following arguments:

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +the `pgsql` block has the following structure:
... can contain the following arguments:

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +the `redis` block has the following structure:
... can contain the following arguments:

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `kibana` - Indicates whether Kibana deploy is enabled.
deployment

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `monitoring` - (Optional) Indicates whether a monitoring agent is enabled. Defaults to `false`.
the

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `autovacuum` - (Optional) Indicates whether the server should run the autovacuum launcher daemon.
must

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  that may be running at any one time. Valid values are from `1` to `262143`. Defaults to `3`.
все таки наверно can 
any тут не добавляет смысла

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `autovacuum_vacuum_cost_delay` - (Optional) The cost delay value in milliseconds that will be used in automatic `VACUUM` operations.
that is used или просто used

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `autovacuum_vacuum_cost_limit` - (Optional) The cost limit value that will be used in automatic `VACUUM` operations.
used

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `maintenance_work_mem` -  (Optional) The maximum amount of memory in bytes (multiple of 1 KiB) that will be used by maintenance operations,
used

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Valid values are from `1` (in MiB) to `2` (in GiB). Defaults to `67108864` (64 Mib).
from 1 MiB to 2 GiB
(здесь выделять цифры не надо при обозначении диапазона

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Valid values are from `2` to `2147483647` (in MiB). Defaults to `83886080` (80 Mib).
from `2` to `2147483647` MiB

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `max_parallel_maintenance_workers` - (Optional) The maximum number of parallel workers that can be started by a single utility command.
that a single utility command start.

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Valid values are from `0` to `1024`. Defaults to `2`.
that a single Gather node can start.

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Valid values are from `32` to `2147483647` (in MiB). Defaults to `83886080` (80 Mib).
from `32` to `2147483647` MiB

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `monitoring` - (Optional) Indicates whether a monitoring agent is enabled. Defaults to `false`.
the

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `options` - (Optional) Map with other PostgreSQL parameters.
map to (?)

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +If you need to use such parameter, contact [technical support].
such a

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Parameter can be set only if `high_availability` is `true`. Valid values are `asynchronous`, `synchronous`, `synchronous_strict`.
The parameter

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `wal_keep_segments` - (Optional) The minimum number of log files segments that should be kept in the pg_xlog directory,
should -> must
\`\`px_log\`\` (в нашей доке названия папок выделяем

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `work_mem` - (Optional) The base maximum amount of memory in bytes (multiple of 1 KiB) to be used by a query operation (such as a sort or hash table)
кажется, что в доке что-то лишнее добавилось при переводе -- в русском просто The amount of memory

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  before writing to temporary disk files. Valid values are from `64` to `2147483647` (in KiB). Defaults to `4194304` (4 Mib).
from `64` to `2147483647` KiB

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `password` - (Required) The PostgreSQL user password. Value should be 8 to 128 characters and should not contain `'`, `"`,  `` ` `` and `\`.
The value must be 8 to 128 characters long and must not contain

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Value should be 8 to 128 characters and should not contain `'`, `"`,  `` ` `` and `\`.
The value must be 8 to 128 characters long and must not contain

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Parameter can be set only if `high_availability` is `true`.
The parameter

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `monitoring` - (Optional) Indicates whether a monitoring agent is enabled. Defaults to `false`.
the

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `options` - (Optional) Map with other Redis parameters.
Map to (?)

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +If you need to use such parameter, contact [technical support].
such a parameter

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  (clients that cannot be reached even if they look connected). Value should be between non-negative. Defaults to `300`.
The value must be non-negative.

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `auto_created_security_group_ids` - List of security group IDs that were created by CROC Cloud PaaS for the service.
that CROC Cloud created for the service

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `id` - The ID the PaaS service.
of the PaaS service

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +## Attributes Reference
Attribute

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `service_class` - The service class. The value matches `class` parameter of the specified block with service parameters.
или must match ?
matches the `class` parameter

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +For `backup_settings`, in addition to the arguments above, the following attribute is exported:
attributes above (?) выше же атрибуты
Вообще это лишнее, можно короче 
For `backup_settings`, the following attribute is also exported:

2023-10-24 15:38 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +PaaS service can be imported using the `id`, e.g.,
the здесь не надо

2023-10-24 16:16 UTC, DiGa66 requested changes

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +  Retrieves information about a PaaS service.
Retrieve -- это извлекать, тут точно этот смысл должен быть?

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +## Attributes Reference
ед. ч.

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `auto_created_security_group_ids` - List of security group IDs that were created by CROC Cloud PaaS for the service.
that CROC Cloud created for the service

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `data_volume` - The service data volume parameters. The structure of this block is [described below](#data_volume).
The data volume parameters for the service.

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `high_availability` - Indicates whether the service cluster is a high availability cluster.
Indicates whether this is a high-availability service.

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `root_volume` - The service root volume parameters. The structure of this block is [described below](#root_volume).
The root volume parameters for the service.

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `service_type` - The service type. Based on the value of this field, the corresponding block contains service parameters.
This value determines which service parameters are included in the corresponding block.

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `notification_email` - The email address to which a notification that backup was created will be sent.
is sent

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `user_id` - The ID of a user with write access to the bucket in object storage.
write permissions (см. ниже)

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `iops` - The number of read/write operations per second for data volume.
for the data volume

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `size` - The size in GiB of the data volume.
The size of the data volume in GiB.

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `iops` - The number of read/write operations per second for root volume.
for the root volume

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `size` - The size in GiB of the root volume.
The size of the root volume in GiB.

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +## Elasticsearch Attributes Reference
Attributes

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +~> **Note** The following attributes contain default parameter values or values specified by the user on service creation.
or user-defined values when the service is created

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `monitoring` - Indicates whether a monitoring agent is enabled.
the monitoring agent

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +## Memcached Attributes Reference
Attribute

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `monitoring` - Indicates whether a monitoring agent is enabled.
the

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +~> **Note** The following attributes contain default parameter values or values specified by the user on service creation.
or user-define values when the service is created.

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `autovacuum` - Indicates whether the server should run the autovacuum launcher daemon.
must

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `autovacuum_max_workers` - The maximum number of autovacuum processes (other than the autovacuum launcher)
may -> can 
any лишнее

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `autovacuum_vacuum_cost_delay` - The cost delay value in milliseconds that will be used in automatic `VACUUM` operations.
that is used или used

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `autovacuum_vacuum_cost_limit` - The cost limit value that will be used in automatic `VACUUM` operations.
that is used или used

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `maintenance_work_mem` -  The maximum amount of memory in bytes that will be used by maintenance operations,
that is used или used

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `max_parallel_maintenance_workers` - The maximum number of parallel workers that can be started by a single utility command.
that a single utility command can start

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `max_parallel_workers_per_gather` - The maximum number of workers that can be started by a single _Gather_ node.
that a single _Gather_ node can start

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `monitoring` - Indicates whether a monitoring agent is enabled.
the

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `wal_keep_segments` - The minimum number of log files segments that should be kept in the pg_xlog directory,
should -> must
``px_log`` (в нашей доке названия папок выделяем

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `work_mem` - The base maximum amount of memory in bytes to be used by a query operation (such as a sort or hash table)
кажется, что в доке что-то лишнее добавилось при переводе -- в русском просто The amount of memory

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +## Redis Attributes Reference
Attribute

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +~> **Note** The following attributes contain default parameter values or values specified by the user on service creation.
or user-defined values when the service is created

2023-10-24 16:16 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `monitoring` - Indicates whether a monitoring agent is enabled.
the

2023-10-25 13:14 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +    # options format example
Он нужен для демонстрации формата блока options, у меня просто реальных значений для него не нашлось. 
Можно переделать коммент с пояснением

2023-10-25 13:31 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +  Retrieves information about a PaaS service.
Этот глагол часто используется в других датасорсах. Возможно имеется ввиду, что информация для сервиса может быть получена из нескольких запросов, целиком извлечена. Но можно заменить и `Gets`, например.

2023-10-25 13:33 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `service_class` - The service class. The value matches `class` parameter of the specified block with service parameters.
Это значение приходит в ответе, т.е. про него нельзя сказать, что оно должно совпадать.
Артикль добавлю

2023-10-29 14:24 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +* `user` - List of database users with parameters. The structure of this block is [described below](#postgresql-database-user).
Тут есть ограничение на 1000 пользователей

2023-11-01 07:57 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `bucket_name` - (Optional) The name of the bucket in object storage where the service backup will be saved.
Поправила, но в c2 доке тоже используется `will be saved`

2023-11-01 13:29 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `options` - (Optional) Map with other Elasticsearch parameters.
Здесь `Map` как структура данных, которая содержит прочие параметры Elasticsearch. Можно переделать на `A map of other Elasticsearch parameters`

2023-11-01 14:20 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +  that may be running at any one time. Valid values are from `1` to `262143`. Defaults to `3`.
Этот кусочек прям из постгревой доки

2023-11-09 14:50 UTC, astroline commented on website/docs/r/paas_service.html.markdown
> +* `options` - (Optional) Map with other Redis parameters.
Имеется в виду map containing other Redis parameters

2023-11-09 14:50 UTC, astroline commented on website/docs/d/paas_service.html.markdown
> +* `total_memory` - Total RAM in use.
Может быть сдесь еще размерность указать?

2023-11-20 07:27 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `work_mem` - (Optional) The base maximum amount of memory in bytes (multiple of 1 KiB) to be used by a query operation (such as a sort or hash table)
Английская версия соответствует [документации postgresql](https://www.postgresql.org/docs/16/runtime-config-resource.html#GUC-WORK-MEM), скорее на русский перевели не полностью

2023-11-22 09:09 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `monitoring` - (Optional) Indicates whether a monitoring agent is enabled. Defaults to `false`.
Параметр `monitoring` теперь стал блоком. Посмотри, пожалуйста, его описание

2023-11-22 09:12 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `monitoring` - (Optional) Indicates whether a monitoring agent is enabled. Defaults to `false`.
Параметр monitoring теперь стал блоком. Описание поменялось, посмотри, пожалуйста

2023-11-22 09:17 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `max_parallel_maintenance_workers` - (Optional) The maximum number of parallel workers that can be started by a single utility command.
`that a single utility command can start`

2023-11-22 09:27 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `monitoring` - (Optional) Indicates whether a monitoring agent is enabled. Defaults to `false`.
Параметр monitoring теперь стал блоком. Описание поменялось, посмотри, пожалуйста

2023-11-22 09:27 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `options` - (Optional) Map with other PostgreSQL parameters.
Остановилась на варианте `A map containing other PostgreSQL parameters.`

2023-11-22 09:30 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `wal_keep_segments` - (Optional) The minimum number of log files segments that should be kept in the pg_xlog directory,
_pg_log_ выделена теперь курсивом

2023-11-22 09:33 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `monitoring` - (Optional) Indicates whether a monitoring agent is enabled. Defaults to `false`.
Параметр monitoring теперь стал блоком. Описание поменялось, посмотри, пожалуйста

2023-11-22 09:33 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +* `options` - (Optional) Map with other Redis parameters.
Остановилась на варианте `A map containing other Redis parameters.`

2023-11-22 09:58 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +* `monitoring` - Indicates whether a monitoring agent is enabled.
Параметр monitoring теперь стал блоком с новым описанием

2023-11-22 10:17 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +* `monitoring` - Indicates whether a monitoring agent is enabled.
Параметр monitoring теперь стал блоком с новым описанием

2023-11-22 10:28 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +* `monitoring` - Indicates whether a monitoring agent is enabled.
Параметр monitoring теперь стал блоком с новым описанием

2023-11-22 10:51 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +* `work_mem` - The base maximum amount of memory in bytes to be used by a query operation (such as a sort or hash table)
см. [ответ](https://github.com/C2Devel/terraform-provider-croccloud/pull/27#discussion_r1371772774)

2023-11-22 10:54 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +* `monitoring` - Indicates whether a monitoring agent is enabled.
Параметр monitoring теперь стал блоком с новым описанием

2023-11-27 11:29 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +  Retrieves information about a PaaS service.
В итоге решила использовать глагол Provides: `Provides information about a PaaS service.`

2023-11-28 16:39 UTC, DiGa66 requested changes

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `work_mem` - The base maximum amount of memory in bytes to be used by a query operation (such as a sort or hash table)
ссылка правильная? Не понял, что смотреть

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
>  * `persistence_aof` - Indicates whether AOF storage mode is enabled.
213 ... whether the AOF storage mode is enabled.
214 ... whether the RDB storage mode is enabled.
215 ... during which the connection ...
215 по смыслу кажется лучше подойдет retained (maintain -- обслуживается, поддерживается)
217 ... during which the service ...
218 ... (unreachable clients или clients whose connections are lost) мне кажется достаточно без подробностей

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  # Use the predefined provider configuration to connect to CROC Cloud S3 storage
все-таки S3 -- это амазановский бренд, может заменить на object

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +~> Arguments are not editable (changes force new resource) except for blocks with service parameters and `backup_settings`.
changes result in a new resource
changes leads to a new resource

... except for the blocks ... (the здесь фактически означает "все")

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `delete_interfaces_on_destroy` - (Optional) Indicates whether to delete instance network interfaces when the service is destroyed. Defaults to `false`.
the instance network interfaces
(или the network interfaces of an instance)

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `kibana` - (Optional) Indicates whether Kibana deployment is enabled. Defaults to `false`.
the Kibana deployment

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +~> If the parameter name includes a dot, then it cannot be passed in the `options`.
здесь the перед options можно в принципе убрать

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  The value must be 8 to 128 characters long and must not contain `'`, `"`,  `` ` `` and `\`.
the AOF storage mode
the RDB storage mode
и аналогичные исправления см. выше в аналогичном случае

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `service_class` - The service class. The value matches `class` parameter of the specified block with service parameters.
в итоге забыла артикль добавить

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +~> This example uses the VPC and subnet defined in [elasticsearch service example](#elasticsearch-service).
in the [Elasticsearch Service example]

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +~> This example uses the VPC and subnet defined in [elasticsearch service example](#elasticsearch-service).
in the [Elasticsearch Service example]

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  The parameter is supported only for [PostgreSQL](#postgresql-argument-reference) service.
for a

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +  that can be running simultaneously.
можно просто can run

2023-11-28 16:39 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  that can be running simultaneously. Valid values are from 1 to 262143. Defaults to `3`.
можно просто can run

2023-11-28 19:07 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +~> Arguments are not editable (changes force new resource) except for blocks with service parameters and `backup_settings`.
Теперь `changes lead to a new resource`

2023-11-29 13:27 UTC, DiGa66 approved these changes

2023-12-03 22:08 UTC, astroline commented on website/docs/d/paas_service.html.markdown
> +* `class` - The service class.
А почему класс у нас вынесень отдельно для каждого сервиса? Он есть у всех, только значения различаются

2023-12-06 14:52 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +* `class` - The service class.
С точки зрения конфигурации этот параметр class будет доступен как `<service_name>.class`, поэтому он добавлен отдельно для каждого сервиса. Также его значение совпадает с параметром `service_class`, который является общим параметром для всех.

Это сделано, чтобы задавать класс при создании сервиса в формате:
```
redis {
  class = database
}
```

2023-12-08 14:29 UTC, astroline approved these changes

2024-01-11 11:39 UTC, merged