PaaS Backup: add resource and datasources with docs; support MongoDB, MySQL, RabbitMQ
C2Devel/terraform-provider-croccloud pull request #30
Opened 2023-12-06 13:52 UTC by PixarV

Based on #27

2023-12-12 16:16 UTC, astroline approved these changes

2023-12-13 16:44 UTC, DiGa66 requested changes

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +~> If the parameter name includes a dot, then it cannot be passed in the `options`.
a parameter name
then можно убрать

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_backup_users.html.markdown
> +  Provides information about users with PaaS Backup User project privileges.
... with the ...

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_backup_users.html.markdown
> +Provides information about users with PaaS Backup User project privileges.
... with the ...

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_backup_users.html.markdown
> +    * `email` - The email address of the user.
в англ. обычно просто email
The user email.

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_backup_users.html.markdown
> +    * `modify_time` - The time when user data was last modified in [RFC3339 format].
А что здесь имеется ввиду под user data? Если данные о самом пользователе, то надо поменять, п.ч. user data у нас имеет другой смысл (пользовательские настройки для сервиса).
user info, user credentials и т.п.

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_backup_users.html.markdown
> +    * `grants` - List of user project privileges.
давай user's

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_backup.html.markdown
> +~> If more than one backup matches specified criteria, the most recently created backup is returned.
meets the specified criteria

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_backup.html.markdown
> +~> `id` cannot be specified together with other parameters.
the other parameters

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_backup.html.markdown
> +* `protected` -  Indicates whether the backup is protected from automatic deletion.
может scheduled deletion (?)

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `gcs_fc_master_slave` -  Galera parameter. Indicates whether the cluster has only one source node.
а тут не лишний пробел после дефиса? тогда убрать здесь и в других местах

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +* `max_allowed_packet` - The maximum size of one packet or any generated/intermediate string,
если тут перечисление из 3 сущностей, то достаточно одного "or"
one packet, any generated/intermediate string or any parameter

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `gcache_size` - (Optional) Galera parameter. The size of GCache circular buffer storage preallocated on startup in bytes. Galera parameter.
2 раза Galera parameter

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `gcs_fc_limit` - (Optional) Galera parameter. The number of writesets. If the recv queue length exceeds it replication is suspended.
A Galera parameter (в др. местах тоже)

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  Valid values are from 5242880 (5 MiB) to 4611686018427387903. Defaults to `134217728` (128 MiB).
а для этого 4611686018427387903 не надо указать значение в МиБ ?

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +* `max_allowed_packet` - (Optional) The maximum size of one packet or any generated/intermediate string,
оставить одно "or" (был аналог. коммент)

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +~> If the parameter name includes a dot, then it cannot be passed in `options`.
a parameter name и в других местах

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_backup.html.markdown
> +* `backup_id` - (Required) The ID of the existed PaaS service backup (e.g. `paas-backup-12345678`).
existing, если существующей

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_backup.html.markdown
> +* `enable_deletion_protection` - (Optional) Indicates whether the backup must be protected from **automatic** deletion.
а зачем здесь выделение automatic?
scheduled?

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_backup.html.markdown
> +  If the parameter is set to `false`, the backup will only be removed from Terraform state. Defaults to `false`.
the Terraform state

2023-12-13 16:44 UTC, DiGa66 commented on website/docs/r/paas_backup.html.markdown
> +~> Terraform does not _create_ a backup for the PaaS service, instead attempts to "adopt" it into management.
Terraform does not create backups, but tries to gain control over an already created backup.

2023-12-14 08:18 UTC, PixarV commented on website/docs/d/paas_backup_users.html.markdown
> +    * `modify_time` - The time when user data was last modified in [RFC3339 format].
Имеются ввиду данные пользователя, использую `user info`

2023-12-14 08:24 UTC, DiGa66 commented on website/docs/d/paas_service.html.markdown
> +~> **Note** The following attributes contain default parameter values or user-defined values when the service is created.
все смотрю на эту фразу, проверил по переводчикам, все одинаково переводят на русский, что кажется имеет не совсем тот смысл:
_Следующие атрибуты содержат значения параметров по умолчанию или определяемые пользователем при создании службы._
Как понимаю, смысл должен быть таким:
_Следующие атрибуты содержат значения параметров по умолчанию или пользовательские значения, используемые при создании службы._
Тогда давай так поменяем
The following attributes contain default parameter values or user-defined values used when the service is created.

2023-12-14 08:29 UTC, DiGa66 commented on website/docs/r/paas_service.html.markdown
> +  A floating-point number. Valid values are from `0.25`.
не совсем понятно, что значит "от 0,25"? В какую сторону? 
Valid values are greater or equal ...

2023-12-14 08:38 UTC, DiGa66 commented on website/docs/r/paas_backup.html.markdown
> +* `enable_deletion_protection` - (Optional) Indicates whether the backup must be protected from **automatic** deletion.
automatic может вызвать вопрос, а при каких условиях удаляется?
может тогда "automatic scheduled deletion"
Не уверен, что надо прям выделять жирным, но во всяком случае надо сделать единообразно с тем, где еще упоминается автоматическое удаление.

2023-12-14 08:40 UTC, DiGa66 commented on website/docs/r/paas_backup.html.markdown
> +~> Terraform does not delete the backup when running `terraform destroy`, it will only be removed from Terraform state.
the Terraform state

2023-12-14 08:45 UTC, PixarV commented on website/docs/r/paas_service.html.markdown
> +  Valid values are from 5242880 (5 MiB) to 4611686018427387903. Defaults to `134217728` (128 MiB).
Оно не кратно 1024, т.е. можно только дробное значение использовать. В [документации](https://dev.mysql.com/doc/refman/8.0/en/innodb-parameters.html#sysvar_innodb_buffer_pool_size) используется MiB для дефолтного значения, а min и max указываются без размерности.

2023-12-14 11:32 UTC, PixarV commented on website/docs/d/paas_backup.html.markdown
> +* `protected` -  Indicates whether the backup is protected from automatic deletion.
Поправила на `automatic scheduled deletion`

2023-12-14 11:36 UTC, PixarV commented on website/docs/d/paas_service.html.markdown
> +* `gcs_fc_master_slave` -  Galera parameter. Indicates whether the cluster has only one source node.
Лишний, убрала тут и прошлась по остальным файлам

2023-12-14 12:11 UTC, PixarV commented on website/docs/r/paas_backup.html.markdown
> +~> Terraform does not delete the backup when running `terraform destroy`, it will only be removed from Terraform state.
Перенесла в верхнюю часть страницы до аргументов

2023-12-14 12:13 UTC, PixarV commented on website/docs/r/paas_backup.html.markdown
> +~> Terraform does not _create_ a backup for the PaaS service, instead attempts to "adopt" it into management.
Теперь `~> Terraform does not create backups of the PaaS service, but tries to gain control over an already created backup.`

2023-12-14 16:00 UTC, DiGa66 approved these changes

2024-01-11 11:42 UTC, merged