paas_service: add proper type casting for mongodb storage_engine_cache_size
C2Devel/terraform-provider-croccloud pull request #39
Opened 2024-04-02 12:30 UTC by avmlds

2024-04-03 11:39 UTC, PixarV requested changes
Добавь еще пожалуйста в заголовок ПРа имя параметра, для которого каст поправлен

2024-04-03 11:39 UTC, PixarV commented on internal/service/paas/services/mongodb.go
> +	storage_engine_cache_size, storage_engine_cache_size_ok := tfMap["storage_engine_cache_size"]
Переведи все переменные в camelCase, пожалуйста

2024-04-03 11:39 UTC, PixarV commented on internal/service/paas/services/mongodb.go
> +		} else if intSize, integerOk := storage_engine_cache_size.(int64); integerOk {
Разве из схемы сейчас может прийти не `float64`?

2024-04-03 11:39 UTC, PixarV commented on internal/service/paas/services/mongodb.go
> +	if storage_engine_cache_size_ok {
Нужна еще проверка, что там не 0 (`v != 0.0` в прошлой версии). В мапе будет 0, если параметр не указан в конфигурации

2024-04-03 11:39 UTC, PixarV commented on internal/service/paas/services/mongodb.go
> +			if intVal, integerOk := v.(int64); integerOk {
Может `int64Val, int64Ok` ?

2024-04-03 12:55 UTC, avmlds commented on internal/service/paas/services/mongodb.go
> +		} else if intSize, integerOk := storage_engine_cache_size.(int64); integerOk {
Да, может. Проблема была именно в том, что когда приходит число без дробной части, оно конвертируется в int64

2024-04-03 15:13 UTC, avmlds commented on internal/service/paas/services/mongodb.go
> +	if storage_engine_cache_size_ok {
Оно же кажется и будет 0 в текущей реализации?  Из-за 218 строчки

2024-04-04 11:53 UTC, PixarV commented on internal/service/paas/services/mongodb.go
> +	if storage_engine_cache_size_ok {
Имею ввиду, что значение 0 для этого параметра не должно отправляться в апи.

2024-04-04 12:44 UTC, PixarV approved these changes

2024-05-30 13:42 UTC, merged