cloudwatch: add `aws_cloudwatch_metric_alarm` resource support
C2Devel/terraform-provider-croccloud pull request #51
Opened 2024-07-22 10:39 UTC by nktrnv

FEATURES:
- **New Resource**: `aws_cloudwatch_metric_alarm`

2024-08-16 15:04 UTC, PixarV requested changes

2024-08-16 15:04 UTC, PixarV commented on internal/provider/provider.go
> +	"github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatch"
Перенеси, пожалуйста, импорт вниз

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +page_title: "AWS: aws_cloudwatch_metric_alarm"
```suggestion
page_title: "aws_cloudwatch_metric_alarm"
```

После ребрендинга такой формат

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +Provides a cloudwatch metric alarm resource.
```suggestion
Manages a CloudWatch metric alarm.
```
\+ в `description` ^

Имя сервиса с большой буквы, ресурс с маленькой.

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +CloudWatch Metric Alarm can be imported using the `alarm_name`, e.g.,
```suggestion
CloudWatch metric alarm can be imported using the `alarm_name`, e.g.,
```

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +
Потерял секцию `Attribute Reference` (как минимум в ней будет атрибут `id`)  и в ней блок `Unsupported attributes` с атрибутами, которые не поддерживаются апи, но есть в стейте с каким-то значением.

Как пример см. [r/eks_cluster.html.markdown](https://github.com/C2Devel/terraform-provider-rockitcloud/blob/develop/website/docs/r/eks_cluster.html.markdown)

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +[metrics]: https://docs.k2.cloud/en/services/monitoring/metrics.html
Замени, пожалуйста, `docs.k2.cloud` на старый домен `docs.cloud.croc.ru` в ссылках на документацию. В планах переделать все ссылки, чтобы они указывали rockitcloud доку (ждем актуализации). Мигрировать будет удобнее, если все ссылки будут на одном домене

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +* `actions_enabled` - (Optional) Indicates whether or not actions should be executed during any changes to the alarm's state. Defaults to `true`.
Для описания аргументов возьми пожалуйста формулировки из облачной документации. Они похожи на те, что используются тут, но более аккуратные.

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +* `alarm_actions` - (Optional) The list of actions to execute when this alarm transitions into an ALARM state from any other state. Each action must be between 1-1024 characters in length. You can sp
ALARM -> `ALARM`
аналогично `INSUFFICIENT_DATA` для `insufficient_data_actions` и `OK` для `ok_actions`

Не уверена насчет регистра, в документации для статуса ипользуются строчные буквы. Предлагаю ориентироваться на регистр в ответе апи

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +* `comparison_operator` - (Required) The arithmetic operation to use when comparing the specified Statistic and Threshold. The specified Statistic value is used as the first operand. Either of the fo
`statistic` and `threshold` - если тут ссылка на значения, указанные для этих аргументов. Если нет, тогда не очень понятно почему они написаны с большой буквы, я бы изменила на маленькую.

Также для перечисления возможных значений предлагаю ` Valid values are ...`

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +* `threshold` - (Required) The value against which the specified statistic is compared.
Тут наверное `statistic` по аналогии с описанием для `period`

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +* `treat_missing_data` - (Optional) Sets how this alarm is to handle missing data points. The following values are supported: `missing`, `ignore`, `breaching` and `notBreaching`. Defaults to `missing
В документации вместо `notBreaching` используется `non_breaching`. Перепроверь пожалуйста какой вариант правильный

Также для перечисления возможных значений предлагаю ` Valid values are ...`

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +* `statistic` - (Required) The statistic to apply to the alarm's associated metric. Either of the following is supported: `SampleCount`, `Average`, `Sum`, `Minimum`, `Maximum`
Давай везде использовать одинаковую формулировку для перечисления возможных значений: `Valid values are ...`

Не хватает `.` в конце.

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +* `metric_name` - (Required) The name for the alarm's associated metric. See docs for [supported metrics][metrics].
Нет информации про допустимую длину строки

2024-08-16 15:04 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +* `namespace` - (Required) The namespace for the alarm's associated metric. See docs for the [list of namespaces and supported metrics][metrics].
Нет информации про допустимую длину строки

2024-08-16 15:04 UTC, PixarV commented on internal/service/cloudwatch/metric_alarm.go
>  	if verify.CheckISOErrorTagsUnsupported(err) {
Кажется, что эта проверка должна быть сразу после `tags, err := ListTags(conn, arn)` до проверки `if err != nil` для проверки кода ошибки. Если поднять ее выше, то возможно код, связанный с тегами можно будет оставить. Проверь пожалуйста

Без вызова `ListTags` оставлять этот if как будто смысла не имеет, тк он использовался именно для проверки ошибки из ответа этого метода

2024-08-19 11:52 UTC, nktrnv commented on internal/service/cloudwatch/metric_alarm.go
>  			"dimensions": {
Здесь хотел добавить MaxItems, но он не совместим с TypeMap

2024-08-22 13:14 UTC, PixarV approved these changes

2024-11-01 09:36 UTC, PixarV commented on internal/service/cloudwatch/metric_alarm.go
> +			"tags": tftags.TagsSchema(),
Давай совсем теги уберем. Сейчас они в стейт залетают и может создаться впечатление, что они для аларма поддерживаются

2024-11-01 09:36 UTC, PixarV commented on website/docs/r/cloudwatch_metric_alarm.html.markdown
> +* `tags` - A map of tags to assign to the resource. Always empty.
И тут убрать

2024-11-01 09:39 UTC, nktrnv commented on internal/service/cloudwatch/metric_alarm.go
> +			"tags": tftags.TagsSchema(),
Хорошо

2024-11-02 09:18 UTC, PixarV commented on internal/service/cloudwatch/metric_alarm.go
>  func getPutMetricAlarmInput(d *schema.ResourceData, meta interface{}) cloudwatch.PutMetricAlarmInput {
Параметр `meta` трекается линтером как unused, удали его пожалуйста

2024-11-05 13:35 UTC, merged