C2DEVEL-14695: return backup service support
C2Devel/terraform-provider-croccloud pull request #54
Opened 2024-09-16 09:12 UTC by RudeZwloki7

2024-09-17 14:27 UTC, PixarV requested changes
Нужно перепроверить коды ошибок, которые проверяются в некоторых ифах: `backup.ErrCodeResourceNotFoundException`, `backup.ErrCodeInvalidRequestException` и пр

Гитхаб не позволяет удобно писать комменты к необновленному коду, так что комментарии к странице `backup_selection.html.markdown` относятся на самом деле к каждой страничке)

2024-09-17 14:27 UTC, PixarV commented on internal/provider/provider.go
> +	// "github.com/hashicorp/terraform-provider-aws/internal/service/iam"
Лишние закомментированные импорты

2024-09-17 14:27 UTC, PixarV commented on internal/provider/provider.go
> +			"aws_backup_plan":                     backup.ResourcePlan(),
Прогони `go fmt` на измененных файлах или `make fmt` для проекта, много где форматирование неправильное

2024-09-17 14:27 UTC, PixarV commented on internal/conns/config.go
> +	var accountID string
```suggestion
	var accountID, partition string
```

2024-09-17 14:27 UTC, PixarV commented on internal/conns/config.go
> +		var parsedAccountID = strings.Split(c.AccessKey, ":")
```suggestion
		parsedAccountID := strings.Split(c.AccessKey, ":")
```
Советует [styleguide](https://google.github.io/styleguide/go/best-practices.html#initialization)

И кажется, что `parsedAccountID` не совсем корректное название для этой переменной. Может `keyParts` или что-то такое

2024-09-17 14:27 UTC, PixarV commented on internal/conns/config.go
> +		c.Region = ""
К сожалению, так все таки сделать нельзя. Некоторые датасорсы сохраняют значение из этого параметра в качестве id (например, `aws_availability_zones`), а пустое значение как id использовать нельзя. Так что от обнуления региона пока предлагаю отказаться. Обсудим

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +* `advanced_backup_setting` - (Optional) An object that specifies backup options for each resource type. _(Currently unsupported)_.
Неподдерживаемые параметры оформляются иначе. Как пример оформления доки можно использовать `ec2_transit_gateway.html.markdown`

Формулировки для описания параметров можно брать из нашей документации, обычно они более четко сфомулированы.

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
>  ## Attributes Reference
```suggestion
## Attribute Reference
```

Так для каждой странички

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +page_title: "AWS: aws_backup_selection"
```suggestion
page_title: "aws_backup_selection"
```

Так для всех страничек

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/plan.go
> +	if len(advancedBackupSettings.List()) > 0 {
Есть метод `Len`, который тут можно использовать

У aws есть документация со стандартными вариантами маппинга из терраформ конфигурации в параметр апи и обратно. Их можно использовать как базу: https://github.com/C2Devel/terraform-provider-rockitcloud/blob/develop/docs/contributing/data-handling-and-conversion.md#root-typeset-of-resource-and-aws-list-of-structure

\+ похожие условия ниже

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/plan.go
> +	if len(tags) > 0 {
С тегами есть проблема: можно указать блок `default_tags` на уровне конфига провайдера, и тогда он будет пытаться добавить их для каждого ресурса, и это условие даст true. Предлагаю полностью выпилить работу с тегами из ресурса, включая элементы схемы

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
>      schedule          = "cron(0 12 * * ? *)"
Падает с ошибкой `InvalidParameterValue: Cron expression is not valid: There should be exactly 5 fields.`

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_vault.html.markdown
> +Deleting the vault is not supported in security purposes. In most cases, use the backup vault data source for existing default vault instead of the resource.
Это можно оформить в виде замечания:
```
~> <text>
```

Сейчас при дестрое конфигурации с волтом возникает ошибка. Если удаление не поддерживается, на дестрое как вариант можно печатать варнинг и удалять ресурс из состояния.

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/plan.go
> +		if len(advancedBackupSettings.List()) > 0 {
Len + https://github.com/C2Devel/terraform-provider-rockitcloud/blob/develop/docs/contributing/data-handling-and-conversion.md#root-typeset-of-resource-and-aws-list-of-structure

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/selection.go
> +	if len(notResources.List()) > 0{
Len + https://github.com/C2Devel/terraform-provider-rockitcloud/blob/develop/docs/contributing/data-handling-and-conversion.md#root-typeset-of-resource-and-aws-list-of-structure

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/selection.go
> +	if len(conditions)>0{
см https://github.com/C2Devel/terraform-provider-rockitcloud/blob/develop/docs/contributing/data-handling-and-conversion.md#root-typeset-of-resource-and-aws-list-of-structure

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/selection.go
> +			Resources:     flex.ExpandStringSet(d.Get("resources").(*schema.Set)),
Если `resources` - это обновляемый атрибут, нужно убрать из схемы `ForceNew: true` + сейчас он там как опциональный отмечен, а в доке - обязательный

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/selection.go
> +		d.SetId(aws.StringValue(output.SelectionId))
После апдейта по идее не должно требоваться сетить id. `SelectionId` поменяется?

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/selection.go
> +	if d.HasChanges("name", "resources") {
`"iam_role_arn"` тоже можно сюда добавить, раз уж его включаем в запрос

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
>  * `rule_name` - (Required) An display name for a backup rule.
У поля есть валидации в схеме на длину и регехп. Они актуальны для бэкап апи (в доке инфы нет)?
Если актуальны, надо добавить инфу о них в документацию.

Аналогично для  `target_vault_name`. Там они вообще кажется не нужны, тк это имя существующего волта.

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/selection.go
> +				return resource.NonRetryableError(err)
Если любая ошибка - NonRetryable, то сама конструкция retry не нужна. Можно заменить весь блок на что-то типа:
```
output, err := conn.UpdateBackupSelection(input)
if err != nil {
    return fmt.Errorf("error updating Backup Selection: %s", err)
}
```

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/selection.go
> +
Добавь пожалуйста логирование получившегося инпута

2024-09-17 14:27 UTC, PixarV commented on website/docs/d/backup_selection.html.markdown
>  * `name` - The display name of a resource selection document.
Проверить валидации

2024-09-17 14:27 UTC, PixarV commented on internal/service/backup/vault.go
> +	if len(tags) > 0 {
Теги лучше совсем выпилить

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
>  * `start_window` - (Optional) The amount of time in minutes before beginning a backup.
Для поддерживаемых **аргументов**, которые имеют дефолтные значения в схеме, в конце описания добаляется `Defaults to <value>.`

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_vault.html.markdown
>  * `name` - (Required) Name of the backup vault to create.
Проверить валидации

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +Manages selection conditions for AWS Backup plan resources.
```suggestion
Manages selection conditions for backup plan resources.
```
\+ продублировать эту строку в тег `description` выше

Если имеется ввиду сервис, то с большой буквы. Если имеется ввиду ресурс (тут backup plan), то с маленькой.

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +Manages selection conditions for AWS Backup plan resources.
Стараюсь использовать одинаковые формулировки в описании для ресурсов и датасорсов:
- для ресурса: `Manages a/an <resource>. For details about <service>, see the [user documentation](ссылка на облачную доку, если есть страница для сервиса).`
- для датасорса: `Provides information about a/an <resource>.`

В качестве примера смотри страницы для paas_\*, ec2_transit_gateway_\*

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +  iam_role_arn = ""
Это неподдерживаемый параметр (по доке), можно убрать совсем

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +  plan_id      = aws_backup_plan.example.id
Если твой ресурс ссылается на другой ресурс, желательно приложить конфигурацию и для него тоже в пример, чтобы его можно было скопировать и запустить целиком.

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +  resources = [
Кажется из этого списка мы поддерживаем только `aws_ebs_volume.example.arn`. Пример в доке должен быть рабочий + нужна конфигурация для указанных ресурсов

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +* `name` - (Required) The display name of a resource selection document.
Для описания полей лучше брать версию из нашей документации, которая обычно более лаконична и однозначна. Также сюда добавляется информация о валидациях и дефолтных значениях для полей, возможных значениях если они есть. В качестве примера формулировок смотри страницы для paas_\*, ec2_transit_gateway_\*

Для редактируемых полей можно добавить `Editable` в начало. Например, `(Required, Editable)`

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +* `iam_role_arn` - (Required) The ARN of the IAM role that AWS Backup uses to authenticate when restoring and backing up the target resource. See the [AWS Backup Developer Guide](https://docs.aws.ama
Изменить оформление неподдерживаемых полей

При переносе полей в неподдерживаемые атрибуты можно срезать часть описания до первого предложения + ссылки могут быть для нас не актуальны

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +## Attributes Reference
```suggestion
## Attribute Reference
```

Так для всех

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +Backup selection can be imported using the role plan_id and id separated by `|`.
```suggestion
Backup selection can be imported using the `plan_id` and `id` separated by `|`.
```

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +* `id` - Backup Selection identifier
```suggestion
* `id` - The ID of the backup selection.
```

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_vault.html.markdown
>  Provides an AWS Backup vault resource.
```suggestion
Manages a backup vault.
```

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +    start_window             = 60
Прогони таргет ` make website-lint-fix`, он поправит ошибки линтинга (тут выровняет конфигурацию)

2024-09-17 14:27 UTC, PixarV commented on website/docs/r/backup_vault.html.markdown
>    name        = "example_backup_vault"
В примерах в имя лучше добавлять инфу про терраформ, чтобы было понятно откуда ресурс.

Я обычно использую что-то типа `tf-backup-vault`

2024-09-24 10:27 UTC, RudeZwloki7 commented on internal/provider/provider.go
> +	// "github.com/hashicorp/terraform-provider-aws/internal/service/iam"
Убрал

2024-09-24 10:28 UTC, RudeZwloki7 commented on internal/conns/config.go
> +	var accountID string
Поправил

2024-09-24 10:29 UTC, RudeZwloki7 commented on internal/conns/config.go
> +		var parsedAccountID = strings.Split(c.AccessKey, ":")
Поправил, вариант `accessKeyParts` мне кажется норм

2024-09-24 10:48 UTC, RudeZwloki7 commented on internal/service/backup/plan.go
> +	if len(advancedBackupSettings.List()) > 0 {
Поправил

2024-09-24 10:53 UTC, RudeZwloki7 commented on internal/service/backup/plan.go
> +	if len(tags) > 0 {
Выпилил теги для бэкапа

2024-09-24 11:01 UTC, RudeZwloki7 commented on internal/service/backup/plan.go
> +		if len(advancedBackupSettings.List()) > 0 {
Поправил

2024-09-24 11:01 UTC, RudeZwloki7 commented on internal/service/backup/selection.go
> +	if len(notResources.List()) > 0{
Поправил

2024-09-24 11:01 UTC, RudeZwloki7 commented on internal/service/backup/selection.go
> +	if len(conditions)>0{
Поправил

2024-09-24 11:03 UTC, RudeZwloki7 commented on internal/service/backup/selection.go
> +			Resources:     flex.ExpandStringSet(d.Get("resources").(*schema.Set)),
Поправил, сделал `resources` обязательным полем

2024-09-24 11:05 UTC, RudeZwloki7 commented on internal/service/backup/selection.go
> +		d.SetId(aws.StringValue(output.SelectionId))
Это лишнее, убрал

2024-09-24 11:08 UTC, RudeZwloki7 commented on internal/service/backup/selection.go
> +	if d.HasChanges("name", "resources") {
Решили, что `iam_role_arn` будет computed полем

2024-09-24 11:09 UTC, RudeZwloki7 commented on internal/service/backup/selection.go
> +				return resource.NonRetryableError(err)
Поправил

2024-09-24 11:10 UTC, RudeZwloki7 commented on internal/service/backup/selection.go
> +
Добавил

2024-09-24 11:12 UTC, RudeZwloki7 commented on internal/service/backup/vault.go
> +	if len(tags) > 0 {
Убрал в `vault_default`

2024-09-24 15:37 UTC, RudeZwloki7 commented on internal/provider/provider.go
> +			"aws_backup_plan":                     backup.ResourcePlan(),
Прогнал

2024-09-24 15:37 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +* `advanced_backup_setting` - (Optional) An object that specifies backup options for each resource type. _(Currently unsupported)_.
Поправил

2024-09-24 15:37 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
>  ## Attributes Reference
Поправил

2024-09-24 15:38 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +page_title: "AWS: aws_backup_selection"
Убрал

2024-09-24 15:38 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
>      schedule          = "cron(0 12 * * ? *)"
Поправил экзамплы, проверил локально

2024-09-24 15:39 UTC, RudeZwloki7 commented on website/docs/r/backup_vault.html.markdown
> +Deleting the vault is not supported in security purposes. In most cases, use the backup vault data source for existing default vault instead of the resource.
Оформил

2024-09-24 15:40 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
>  * `rule_name` - (Required) An display name for a backup rule.
Добавил инфу по вариациям

2024-09-24 15:42 UTC, RudeZwloki7 commented on website/docs/d/backup_selection.html.markdown
>  * `name` - The display name of a resource selection document.
Добавил инфу по валидациям

2024-09-24 15:42 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
>  * `start_window` - (Optional) The amount of time in minutes before beginning a backup.
Добавил

2024-09-24 15:44 UTC, RudeZwloki7 commented on website/docs/r/backup_vault.html.markdown
>  * `name` - (Required) Name of the backup vault to create.
Убрали `name` из аргументов в соответствии с текущим поведением

2024-09-24 15:45 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +Manages selection conditions for AWS Backup plan resources.
Поправил

2024-09-24 15:45 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +  iam_role_arn = ""
Убрал, сделали computed полем

2024-09-24 15:46 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +  plan_id      = aws_backup_plan.example.id
Добавил

2024-09-24 15:47 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +  resources = [
Протестил еще с инстансом, но решил не пихать, чтобы не увеличивать и так объемный пример. Убрал все кроме ebs volume

2024-09-24 15:47 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +* `name` - (Required) The display name of a resource selection document.
Добавил

2024-09-24 15:48 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +* `iam_role_arn` - (Required) The ARN of the IAM role that AWS Backup uses to authenticate when restoring and backing up the target resource. See the [AWS Backup Developer Guide](https://docs.aws.ama
Поправил

2024-09-24 15:48 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +## Attributes Reference
Поправил

2024-09-24 15:49 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +Backup selection can be imported using the role plan_id and id separated by `|`.
Убрал блок импорта в этом месте, не сработал

2024-09-24 15:50 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +* `id` - Backup Selection identifier
Поправил, взял строку из доки

2024-09-24 15:50 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +    start_window             = 60
поправил

2024-09-24 15:51 UTC, RudeZwloki7 commented on website/docs/r/backup_vault.html.markdown
>  Provides an AWS Backup vault resource.
поправил

2024-09-24 15:51 UTC, RudeZwloki7 commented on website/docs/r/backup_vault.html.markdown
>    name        = "example_backup_vault"
поправил

2024-09-26 15:20 UTC, RudeZwloki7 commented
Обновил коды ошибок

2024-10-04 14:26 UTC, PixarV requested changes
Документацию еще не досмотрела

2024-10-04 14:26 UTC, PixarV commented on internal/provider/provider.go
> +			"aws_backup_vault":     backup.ResourceDefaultVault(),
Я бы добавила совсем новый ресурс `aws_backup_default_vault`, а `aws_backup_vault` оставила закомментированным. Если волты начнут поддерживать CRUD полностью, можно будет открыть доступ к `aws_backup_vault` и точно ничего не поломать

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/vault_default.go
> +
Прогони `make importlint`, по-моему эта пустая строка лишняя

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/plan.go
> +				BackupPlanName: aws.String(d.Get("name").(string)),
Тк у нас можно обновлять имя плана, можно удалить опцию `ForceNew: true` для параметра `name` в схеме + добавить это поле выше в `if d.HasChanges(..)`

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/selection.go
> +	d.Set("iam_role_arn", "")
Немного странно встретить тут `d.Set(..)`

Я бы может сразу указала бы "" в реквесте с поясняющим комментом:
```
	selection := &backup.Selection{
		IamRoleArn: aws.String(""), // FIXME: add explanation
        }
```
А в `resourceSelectionRead` уже засетится значение

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/selection.go
> +		if tfresource.TimedOut(err) {
Вот этот блок можно убрать, он работает с ошибкой, которую возвращает `resource.Retry`  и схлопнуть вызов Update и проверку ошибки до:
```
if _, err := conn.UpdateBackupSelection(input); err != nil {
	return fmt.Errorf("error updating Backup Selection: %s", err)
}
```

2024-10-04 14:26 UTC, PixarV commented on website/docs/d/backup_plan.html.markdown
> +  Provides details about an backup plan.
```suggestion
  Provides information about a backup plan.
```

Эта строка дублируется в описание под именем ресурса 

```
# Data Source: aws_backup_plan

Provides information about a backup plan.
```

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/vault_default.go
> +			"kms_key_arn": {
В ресурсы, которые мы сами добавляем, не нужно включать неподдерживаемые поля.

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/vault_default.go
> +			"recovery_points": {
Тоже не поддерживается

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/vault_default.go
> +	}
Не обрабатывается условие, когда `ListBackupVaults` вернул ошибку, которая != nil и ее код не из `errCodeVaultNotFound`

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/vault_default.go
> +	} else if tfawserr.ErrCodeEquals(err, errCodeVaultNotFound) || len(output.BackupVaultList) == 0 {
`ListBackupVaults` без параметров может вернуть код из `errCodeVaultNotFound`?

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/vault_default.go
> +		_, err = conn.CreateBackupVault(input)
Можно схлопнуть с проверкой ошибки в один if

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/vault_default.go
> +		log.Printf("[INFO] Found existing Backup Vault (%s)", *vault.BackupVaultName)
```suggestion
		log.Printf("[INFO] Found existing Backup Vault (%s)", aws.StringValue(vault.BackupVaultName))
```

Для разыменования обычно используются утильные функции

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/vault_default.go
> +		d.SetId(*vault.BackupVaultName)
`aws.StringValue(..)`

2024-10-04 14:26 UTC, PixarV commented on internal/service/backup/vault_default.go
> +	if err == nil && len(output.BackupVaultList) > 0 {
Предлагаю немного реорганизовать условия, чтобы уменьшить if блоки:

```
if err != nil {
    if tfawserr.ErrCodeEquals(err, errCodeVaultNotFound) || len(output.BackupVaultList) == 0 {
        vault := output.BackupVaultList[0]
        ...
        return resourceDefaultVaultRead(d, meta)
    } else {
        return fmt.Errorf("err explanation")
    }
}

// create logic
...
return resourceDefaultVaultRead(d, meta)
```

2024-10-04 14:26 UTC, PixarV commented on website/docs/d/backup_plan.html.markdown
> +* `tags` - Metadata that you can assign to help organize the plans you create. Excluded from schema.
Можно убрать, тк тэгов больше нет

2024-10-04 14:26 UTC, PixarV commented on website/docs/d/backup_plan.html.markdown
> +  plan_id = "tf-backup-plan-id"
А в каком формате обычно plan_id? если это uuid, то лучше использовать юидообразный шаблон

2024-10-04 14:26 UTC, PixarV commented on website/docs/d/backup_selection.html.markdown
> +  Provides details about an backup selection.
```suggestion
  Provides details about a backup selection.
```

2024-10-04 14:26 UTC, PixarV commented on internal/service/ec2/ebs_volume.go
> +		Region:    "",
Добавь пожалуйста коммент о том, что регион в арнах не поддерживается

2024-10-04 14:26 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +->  **Unsupported arguments**
Я их обычно в раздел `Unsupported attributes` перемещала, тк формально они тут описываются только потому что они есть в итоговом состоянии. И получался один такой раздел на одну страничку в документации

2024-10-04 14:26 UTC, PixarV commented on website/docs/r/backup_vault.html.markdown
> +  Manages an backup vault resource.
```suggestion
  Manages a backup vault resource.
```

2024-10-07 12:04 UTC, RudeZwloki7 commented on internal/service/backup/vault_default.go
> +			"recovery_points": {
recovery points поддерживаются, апиха отдает данные

2024-10-07 13:30 UTC, RudeZwloki7 commented on internal/provider/provider.go
> +			"aws_backup_vault":     backup.ResourceDefaultVault(),
Поправил

2024-10-07 13:30 UTC, RudeZwloki7 commented on internal/service/backup/vault_default.go
> +
Поправил

2024-10-07 13:36 UTC, RudeZwloki7 commented on internal/service/backup/plan.go
> +				BackupPlanName: aws.String(d.Get("name").(string)),
Поправил

2024-10-07 13:40 UTC, RudeZwloki7 commented on internal/service/backup/selection.go
> +	d.Set("iam_role_arn", "")
Поправил проставление значения в запросе + убрал проставление значения в `Read`

2024-10-07 14:20 UTC, RudeZwloki7 commented on internal/service/backup/selection.go
> +		if tfresource.TimedOut(err) {
Поправил

2024-10-07 14:26 UTC, RudeZwloki7 commented on internal/service/ec2/ebs_volume.go
> +		Region:    "",
Поправил в volume и instance ресурсах и датасорсах

2024-10-07 14:37 UTC, RudeZwloki7 commented on internal/service/backup/vault_default.go
> +			"kms_key_arn": {
Убрал `kms_key_arn` из ресурса

2024-10-07 14:51 UTC, RudeZwloki7 commented on internal/service/backup/vault_default.go
> +		_, err = conn.CreateBackupVault(input)
Поправил

2024-10-07 14:52 UTC, RudeZwloki7 commented on internal/service/backup/vault_default.go
> +		d.SetId(*vault.BackupVaultName)
Поправил

2024-10-07 14:52 UTC, RudeZwloki7 commented on internal/service/backup/vault_default.go
> +		log.Printf("[INFO] Found existing Backup Vault (%s)", *vault.BackupVaultName)
Поправил

2024-10-08 07:00 UTC, RudeZwloki7 commented on internal/service/backup/vault_default.go
> +	} else if tfawserr.ErrCodeEquals(err, errCodeVaultNotFound) || len(output.BackupVaultList) == 0 {
Нет, вернет пустой список. Убрал `errCodeVaultNotFound`

2024-10-08 07:02 UTC, RudeZwloki7 commented on internal/service/backup/vault_default.go
> +	}
Добавил обработку ошибки

2024-10-08 08:27 UTC, RudeZwloki7 commented on website/docs/d/backup_plan.html.markdown
> +  plan_id = "tf-backup-plan-id"
Поправил в примерах id на шаблон `01234567-0123-0123-0123-0123456789ab`

2024-10-08 08:39 UTC, RudeZwloki7 commented on website/docs/d/backup_plan.html.markdown
> +* `tags` - Metadata that you can assign to help organize the plans you create. Excluded from schema.
Убрал выпиленные теги из доки по обновленным ресурсам

2024-10-08 08:45 UTC, RudeZwloki7 commented on website/docs/r/backup_vault.html.markdown
> +  Manages an backup vault resource.
Поправил

2024-10-08 08:45 UTC, RudeZwloki7 commented on website/docs/d/backup_selection.html.markdown
> +  Provides details about an backup selection.
Поправил

2024-10-08 08:46 UTC, RudeZwloki7 commented on website/docs/d/backup_plan.html.markdown
> +  Provides details about an backup plan.
Поправил

2024-10-08 09:20 UTC, RudeZwloki7 commented on internal/service/backup/vault_default.go
> +	if err == nil && len(output.BackupVaultList) > 0 {
Поправил

2024-10-08 11:33 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +->  **Unsupported arguments**
Поправил

2024-10-14 08:07 UTC, PixarV requested changes

2024-10-14 08:07 UTC, PixarV commented on website/docs/d/backup_plan.html.markdown
> +  Provides information about a backup plan.
```suggestion
Provides information about a backup plan.
```

2024-10-14 08:07 UTC, PixarV commented on website/docs/d/backup_selection.html.markdown
> +In addition to all arguments above, the following attributes are available:
```suggestion
In addition to all arguments above, the following attributes are exported:
```

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +[Backup]: https://docs.cloud.croc.ru/en/services/backup/operations.html#backupplan
```suggestion
[backup-plan]: https://docs.cloud.croc.ru/en/services/backup/operations.html#backupplan
```

На случай, если еще ссылки из этого раздела появятся ) + обновить в месте использования

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +* `rule` - (Required, Editable) A rule object that specifies a separate periodic task.
Тут на самом деле список объектов

В конфигурации будет указываться так:
```
resource "aws_backup_plan" "example" {
  name = "tf-backup-plan"
  
  rule {...}
  
  rule {...}
}
```

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +* `rule` - (Required, Editable) A rule object that specifies a separate periodic task.
Для перехода к описанию внутренней структуры блока добавь в конец предложение: `The structure of the block is [described below](#rule).`. 

`#rule` - это ссылка на соответствующий заголовок внизу, там будет `### Rule` вместо `### Rule Arguments`

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +For **rule** the following arguments are supported:
Используй тут такую формулировку: ``The `rule` block has the following structure:``

Еще до этого предложения можно добавить такой блок, если все параметры редактируемые:
``~> All the parameters in the `rule` block are editable.``

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +* `lifecycle` - (Optional) The lifecycle defines when a protected resource is transitioned to cold storage and when it expires. Fields documented below.
```suggestion
* `lifecycle` - (Optional) The lifecycle defines when a protected resource is transitioned to cold storage and when it expires. The structure of the block is [described below](#lifecycle).
```

Правки как для `rule`

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +* `rule_name` - (Required) The name of the backup rule. Must be at least `1` character and at most `50` characters in length. Must contain only alphanumeric characters, hyphens, underscores, and peri
```suggestion
* `rule_name` - (Required) The name of the backup rule. The value must be 1 to 50 characters long and must contain only alphanumeric characters, hyphens, underscores, and periods.
```

Так чуть короче

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +* `name` - (Required) The name of the backup plan.
Тожe Editable

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +* `target_vault_name` - (Required) The name of the backup vault. Must be at least `2` characters and at most `50` characters in length. Must contain only alphanumeric characters, hyphens, and undersc
```suggestion
* `target_vault_name` - (Required) The name of the backup vault. The value must be 2 to 50 characters long and must contain only alphanumeric characters, hyphens, and underscores.
```

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +### Lifecycle Arguments
см. комментарии для rule

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_vault_default.html.markdown
> +->  **Unsupported attributes**
Этот блок тут не нужен

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_vault_default.html.markdown
> +resource "aws_backup_vault_default" "example" {
```suggestion
resource "aws_backup_vault_default" "example" {}
```

Указать в одну строку немного компактнее. \+ поправить в остальных примерах.

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_vault_default.html.markdown
> +* `recovery_points` - The number of recovery points in the vault.
```suggestion
* `recovery_points` - The number of recovery points in the backup vault.
```

Раз уж везде выше `the backup vault`

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +  type              = "standard"
возьми тут `gp2` лучше

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_vault_default.html.markdown
> +Backup vault can be imported using the `name`, e.g.,
```suggestion
Backup vault can be imported using `name`, e.g.,
```

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +Backup Plan can be imported using the `id`, e.g.,
```suggestion
Backup Plan can be imported using `id`, e.g.,
```

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +* `name` - (Required, Editable) The selection name. Must be at least `1` character and at most `50` characters in length. Must contain contain only alphanumeric, hyphen, underscore, and period charac
```suggestion
* `name` - (Required, Editable) The selection name. The value must be 1 to 50 characters long and must contain contain only alphanumeric, hyphen, underscore, and period characters.
```

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_selection.html.markdown
> +* `condition` - A list of conditions that you define to assign resources to your backup plans using tags.
`Always empty` вероятно потерял + ниже

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_vault_default.html.markdown
> +~> Deleting the vault is not supported in security purposes.
Есть такая формулировка: ``~> Terraform does not delete the default backup vault when running `terraform destroy`, it will only be removed from the Terraform state.``

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_vault_default.html.markdown
> +Manages a backup vault resource.
Я бы переписала эту пару строк как-нибудь так:
```
Manages the default backup vault. If it doesn't exist, Terraform will create one.
```

\+ поправить в description

2024-10-14 08:07 UTC, PixarV commented on website/docs/r/backup_plan.html.markdown
> +Manages a backup plan resource. For details about backup plans, see the [user documentation][Backup].
```suggestion
Manages a backup plan. For details about backup plans, see the [user documentation][Backup].
```

2024-10-15 07:37 UTC, RudeZwloki7 commented on internal/conns/config.go
> +		c.Region = ""
Вместо обнуления региона в конфиге перенесли проставление пустого региона при построении ARN провайдером в бэкапируемых сущностях

2024-10-15 07:41 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +Backup selection can be imported using the role plan_id and id separated by `|`.
Вернул

2024-10-15 07:49 UTC, RudeZwloki7 commented on website/docs/r/backup_vault_default.html.markdown
> +Backup vault can be imported using the `name`, e.g.,
Поправил

2024-10-15 07:50 UTC, RudeZwloki7 commented on website/docs/r/backup_vault_default.html.markdown
> +* `recovery_points` - The number of recovery points in the vault.
Поправил

2024-10-15 07:51 UTC, RudeZwloki7 commented on website/docs/r/backup_vault_default.html.markdown
> +->  **Unsupported attributes**
Убрал

2024-10-15 07:53 UTC, RudeZwloki7 commented on website/docs/r/backup_vault_default.html.markdown
> +resource "aws_backup_vault_default" "example" {
Поправил

2024-10-15 07:54 UTC, RudeZwloki7 commented on website/docs/r/backup_vault_default.html.markdown
> +~> Deleting the vault is not supported in security purposes.
Поправил

2024-10-15 07:55 UTC, RudeZwloki7 commented on website/docs/r/backup_vault_default.html.markdown
> +Manages a backup vault resource.
Поправил

2024-10-15 08:02 UTC, RudeZwloki7 commented on website/docs/d/backup_plan.html.markdown
> +  Provides information about a backup plan.
Поправил

2024-10-15 08:10 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +Manages a backup plan resource. For details about backup plans, see the [user documentation][Backup].
Поправил

2024-10-15 08:13 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +[Backup]: https://docs.cloud.croc.ru/en/services/backup/operations.html#backupplan
Поправил

2024-10-15 08:14 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +* `name` - (Required) The name of the backup plan.
Поправил

2024-10-15 08:44 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +* `rule` - (Required, Editable) A rule object that specifies a separate periodic task.
Добавил еще один блок `rule` в примерах конфигураций + в описании поля `rule`

2024-10-15 08:47 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +For **rule** the following arguments are supported:
Поправил

2024-10-15 08:48 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +* `lifecycle` - (Optional) The lifecycle defines when a protected resource is transitioned to cold storage and when it expires. Fields documented below.
Поправил

2024-10-15 08:49 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +* `rule_name` - (Required) The name of the backup rule. Must be at least `1` character and at most `50` characters in length. Must contain only alphanumeric characters, hyphens, underscores, and peri
Поправил

2024-10-15 08:50 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +* `target_vault_name` - (Required) The name of the backup vault. Must be at least `2` characters and at most `50` characters in length. Must contain only alphanumeric characters, hyphens, and undersc
Поправил

2024-10-15 08:50 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +### Lifecycle Arguments
Поправил

2024-10-15 08:54 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +Backup Plan can be imported using the `id`, e.g.,
Поправил

2024-10-15 09:06 UTC, RudeZwloki7 commented on website/docs/d/backup_selection.html.markdown
> +In addition to all arguments above, the following attributes are available:
Поправил

2024-10-15 09:06 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +  type              = "standard"
Поправил

2024-10-15 09:07 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +* `name` - (Required, Editable) The selection name. Must be at least `1` character and at most `50` characters in length. Must contain contain only alphanumeric, hyphen, underscore, and period charac
Поправил

2024-10-15 09:08 UTC, RudeZwloki7 commented on website/docs/r/backup_selection.html.markdown
> +* `condition` - A list of conditions that you define to assign resources to your backup plans using tags.
Поправил

2024-10-17 16:03 UTC, DiGa66 requested changes

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/d/backup_plan.html.markdown
> +* `version` - Unique, randomly generated, Unicode, UTF-8 encoded string that serves as the version ID of the backup plan. Always `""`.
that serves as -> used as

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/d/backup_selection.html.markdown
> +* `iam_role_arn` - The Amazon Resource Name (ARN) of the role used for authentication when the resource is backed up (not implemented, added to ensure compatibility with AWS). Always `""`.
надо ли писать про то, что не реализовано, если раздел называется "Неподдерживаемые атрибуты)
я бы убрал весь текст в скобках

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/d/backup_selection.html.markdown
> +* `resources` - The list of Amazon Resource Names (ARNs) resources included into the backup plan.
of the resources

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/d/backup_selection.html.markdown
> +* `plan_id` - (Required) The backup plan ID.
для единообразия тогда уж
The ID of the backup plan

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `rule` - (Required, Editable) List of rule objects for separate periodic tasks. The structure of this block is [described below](#rule)
может просто rules ? в следующем предложении пишем, что это блок

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `completion_window` - (Optional) Time in minutes after the start of the backup job, during which it should be completed. Otherwise, it will be canceled. Defaults to `180`.
по красоте after the backup job is started, но необ.

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `lifecycle` - (Optional) The lifecycle defines when a protected resource is transitioned to cold storage and when it expires. The structure of the block is [described below](#lifecycle).
transitioned скорее трансформация
tranferred

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `rule_name` - (Required) The name of the backup rule. The value must be `1` to `50` characters long and must contain only alphanumeric characters, hyphens, underscores, and periods.
and -> or

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `delete_after` - (Optional, Editable) Number of days from the recovery point creation date, after which it will be deleted.
the date of creation of the restore point

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +    * `lifecycle` - The lifecycle defines when a protected resource is transitioned to cold storage and when it expires.
Defines ...
transferred

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +        * `cold_storage_after` - Specifies the number of days after creation that a recovery point is moved to cold storage.
after creation of the recovery point after which it

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `version` - Unique, randomly generated, Unicode, UTF-8 encoded string that serves as the version ID of the backup plan. Always `""`.
that servers -> used

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +    * `recovery_point_tags` - Metadata that you can assign to help organize the resources that you create.
не оч. понятно, что значит organize в этом контексте

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `id` - The backup plan ID.
см. выше

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +    * `enable_continuous_backup` - Enable continuous backups for supported resources. Defaults to `false`.
Enables

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `advanced_backup_setting` - An object that specifies backup options for each resource type. Always empty.
Specifies ... (начало убрать)

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `rule` - A rule object that specifies a separate periodic task.
Specifies ...

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +Backup Plan can be imported using `id`, e.g.,
plan

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_selection.html.markdown
> +* `name` - (Required, Editable) The selection name. The value must be `1` to `50` characters long and must contain only alphanumeric, hyphen, underscore, and period characters.
лучше: 
alphanumeric characters, hyphens, underscores, and periods.
и в других местах поменять

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_selection.html.markdown
> +* `plan_id` - (Required) The backup plan ID.
ID of ...

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_selection.html.markdown
> +* `resources` - (Required, Editable) The list of Amazon Resource Names (ARNs) resources included into the backup plan.
of the resources

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_selection.html.markdown
> +* `iam_role_arn` -  The Amazon Resource Name (ARN) of the role used for authentication when the resource is backed up (not implemented, added to ensure compatibility with AWS). Always `""`.
нужен текст в скобках?

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_selection.html.markdown
> +* `not_resources` - An array of strings that either contain Amazon Resource Names (ARNs) or match patterns of resources to exclude from a backup plan. Always empty.
массив же содержит? тогда
contains
matches

that contains either Amazon Resource Names (ARNs) or match patterns of resources to be excluded from a backup plan. Always empty.

2024-10-17 16:03 UTC, DiGa66 commented on website/docs/r/backup_vault_default.html.markdown
> +* `id` - The name of the backup vault.
The ID

2024-10-18 04:36 UTC, RudeZwloki7 commented on website/docs/d/backup_selection.html.markdown
> +* `iam_role_arn` - The Amazon Resource Name (ARN) of the role used for authentication when the resource is backed up (not implemented, added to ensure compatibility with AWS). Always `""`.
Конкретно по этому полю не реализована бизнес логика, но оно все еще обязательное в схеме и бэк проверяет его наличие в запросе. Сейчас подставляем дефолтное значение на уровне провайдера, чтобы облегчить жизнь пользователю. Думаю, совсем убирать не стоит, т.к. поле используется. Может просто описание поправить на более понятное?

2024-10-18 05:07 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +    * `recovery_point_tags` - Metadata that you can assign to help organize the resources that you create.
У aws по тегам много где такая формулировка фигурирует. Как я понял, они подразумевают под organize управление в плане поиска, фильтрации, группировки ресурсов по их тегам

2024-11-05 13:29 UTC, PixarV approved these changes

2024-11-05 14:32 UTC, DiGa66 approved these changes

2024-11-05 14:32 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +* `completion_window` - (Optional) Time in minutes after the backup job is started, during which it should be completed. Otherwise, it will be canceled. Defaults to `180`.
cancelled

2024-11-05 14:32 UTC, DiGa66 commented on website/docs/r/backup_plan.html.markdown
> +    * `lifecycle` - Defines when a protected resource is transferred to cold storage and when it expires.
а тут все правильно? Как сам экземпляр (защищаемый ресурс) может быть перемещен в cold storage?

2024-11-05 14:59 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +* `completion_window` - (Optional) Time in minutes after the backup job is started, during which it should be completed. Otherwise, it will be canceled. Defaults to `180`.
Поправил

2024-11-05 15:11 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +    * `lifecycle` - Defines when a protected resource is transferred to cold storage and when it expires.
Т.к. этот атрибут неподдерживаемый, за основу взята формулировка от aws. По идее такие формулировки не особо критичны, пока у нас нет нашей реализации, под которую можно четко описать эти атрибуты. КМК можно оставить и protected resource, если воспринимать это больше как абстракцию, что мы бэкапим этот ресурс и у него есть точки восстановления. И в зависимости от даты последних точек восстановления можно судить насколько протух/актуален бэкапируемый ресурс в нашем хранилище

2024-11-05 15:26 UTC, RudeZwloki7 commented on website/docs/r/backup_plan.html.markdown
> +    * `lifecycle` - Defines when a protected resource is transferred to cold storage and when it expires.
Обсудили, лучше исправить на recovery point

2024-11-05 15:33 UTC, merged