add iam resources support
C2Devel/terraform-provider-croccloud pull request #55
Opened 2024-10-01 08:31 UTC by PixarV

2024-10-04 15:28 UTC, DiGa66 reviewed
Продолжу на след. неделе

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_group.html.markdown
> +~> Filtering by `name` is done locally and could have a performance impact if the list of groups is large.
is performed locally and can affect performance when

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_group.html.markdown
> +* `create_date` - The time when the group was created in [RFC3339 format].
The time in [RFC3339 format] when ...

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_policy.html.markdown
> +~> Filtering by `name` is done locally and could have a performance impact if the list of policies is large.
is performed locally and can affect performance when

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_policy.html.markdown
> +In addition to all arguments above, the following attributes are exported:
а мы решили all? Можно просто the

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_policy.html.markdown
> +* `create_date` - The time when the policy was created in [RFC3339 format].
The time in [RFC3339 format] when ...

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_policy.html.markdown
> +* `update_date` - The time when the policy was last updated in [RFC3339 format].
The time in [RFC3339 format] when

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_project.html.markdown
> +* `create_date` - The time the project was created in [RFC3339 format].
The time in [RFC3339 format] when ...

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_user.html.markdown
> +* `last_login_date` - The time when the user last logged in to the web interface in [RFC3339 format].
The time in [RFC3339 format] when

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_user.html.markdown
> +* `update_date` - The time the user was last updated in [RFC3339 format].
The time in [RFC3339 format] when

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_user.html.markdown
> +* `path` - Path in which this user was created. Always `""`.
не оч понятно, что хотела сказать

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_user.html.markdown
> +* `permissions_boundary` - The ARN of the policy that is used to set the permissions boundary for the user. Always `""`.
не оч понятно

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_users.html.markdown
> +* `path_prefix` - The path prefix for filtering the results. Always empty.
to filter results

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/d/iam_users.html.markdown
> +~> This filtering is done locally and could have a performance impact if the list of users is large.
is performed locally and can affect performance when

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group.html.markdown
> +For this reason, it's recommended to either manage membership entirely with Terraform or entirely within the cloud console.
to manage membership either entirely using Terraform or entirely in the cloud console.

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group.html.markdown
> +In addition to all arguments above, the following attributes are exported:
the arguments

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group.html.markdown
> +* `create_date` - The time when the group was created in [RFC3339 format].
порядок

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group.html.markdown
> +* `path` - Path in which to create the group. Always `""`.
не  оч понятно

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group.html.markdown
> +* import group provided by customer `test.customer` named `group-example`:
import a group  `group-example` provided by a customer `test.customer`

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group.html.markdown
> +  plus (+) and equals (=) signs, commas (,), periods (.), at symbols (@) and hyphens (-) (`^[\w+=,.@-]*$`).
equal

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group.html.markdown
> +in addition to manually managing user/group membership using the cloud console may lead to configuration drift or conflicts.
Manually managing user/group membership via the cloud console alongside using aws_iam_group_membership or aws_iam_user_group_membership resources may result in ...
так попроще конструкция будет

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group_membership.html.markdown
> +~> Use this resource no more than once per group to avoid inconsistent behavior.
Use no more than one resource per group ...

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group_membership.html.markdown
> +To manage a specific user in multiple groups,
How to ...

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group_membership.html.markdown
> +In addition to all arguments above, the following attributes are exported:
the

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group_membership.html.markdown
> +* `project` - (Optional) The name of the project, which is specified when users are added to a project group.
The name of the project. Specified when users are added to a project group.

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group_policy_attachment.markdown
> +* `id` - The `group_arn` and `policy_arn` separated by a hash sign (`#`).
The артикль не нужен

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_group_policy_attachment.markdown
> +IAM group policy attachments can be imported using the `id`, e.g.,
не нашел такого понятия у AWS "group policy attachment"
не нужен the

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +  # Terraform's "jsonencode" function converts a
артикль лучше не разрывать со словом

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +  # Terraform expression result to valid JSON syntax.
the result of a Terraform expression into the correct JSON syntax.

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +* `name` - (Optional, Conflicts with `name_prefix`) The name of the policy. The value can only contain Latin letters, numbers, underscores (_),
Conflicts откуда-то взято?

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +  plus (+) and equals (=) signs, commas (,), periods (.), at symbols (@) and hyphens (-) (`^[\w+=,.@-]*$`).
equal

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +* `name_prefix` - (Optional, Conflicts with `name`) Creates a unique name beginning with the specified prefix.
переводчики предлагают starting)

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +~> If `name` and `name_prefix` are omitted, Terraform will assign a random, unique name prefixed with `terraform-`.
зпт не нужна
with the `terraform-` prefix

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +In addition to all arguments above, the following attributes are exported:
the

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +* `create_date` - The time when the policy was created in [RFC3339 format].
порядок

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +* `update_date` - The time when the policy was last updated in [RFC3339 format].
порядок

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +* import policy provided by customer `test.customer` named `policy-example`:
import a policy `policy-example` provided by a customer `test.customer`:

2024-10-04 15:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +  The value must be no more than 1000 characters long.
no longer that (короче)

2024-10-06 12:52 UTC, PixarV commented on website/docs/d/iam_policy.html.markdown
> +In addition to all arguments above, the following attributes are exported:
Тут взяли без изменений формулировку от aws.

2024-10-06 12:57 UTC, PixarV commented on website/docs/d/iam_user.html.markdown
> +* `path` - Path in which this user was created. Always `""`.
Это неподдерживаемый нами атрибут. Сохранила описание, которое было в оригинальной документации

2024-10-06 12:57 UTC, PixarV commented on website/docs/d/iam_user.html.markdown
> +* `permissions_boundary` - The ARN of the policy that is used to set the permissions boundary for the user. Always `""`.
Это неподдерживаемый нами атрибут. Сохранила описание, которое было в оригинальной документации

2024-10-07 07:57 UTC, PixarV commented on internal/service/iam/user.go
> +			"password": {
Добавить `Sensitive: true` + для `secret_key`

Нужно будет поправить пример в доке

2024-10-07 09:41 UTC, DiGa66 requested changes

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_project.html.markdown
> +* `create_date` - The time the project was created in [RFC3339 format].
порядок

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user.html.markdown
> +~> Usernames are not case-sensitive. For example, you cannot create users named both "TESTUSER" and "testuser".
For example, you cannot create users named "TESTUSER" and "testuser" at the same time.

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user.html.markdown
> +* `password` - (Optional, Editable) The password of the user. If no value is specified, the password will be generated.
хочется добавить generated automatically.

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user.html.markdown
> +* `last_login_date` - The time when the user last logged in to the web interface in [RFC3339 format].
The time in [RFC3339 format] when the user last logged in to the web interface.

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user.html.markdown
> +* `update_date` - The time the user was last updated in [RFC3339 format].
The time in [RFC3339 format] when

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user.html.markdown
> +~> `password` and `secret_key` are exported once when the user is created and will not be updated after that.
only once
after that -> afterwards

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user.html.markdown
> +* `force_destroy` - When destroying this user, destroy even if it has non-Terraform-managed IAM access keys,
Мне кажется лишнее уточнение, достаточно:
The user will be destroyed even if its IAM access keys, login profile or MFA devices are not managed by Terraform.

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user.html.markdown
> +* `permissions_boundary` - The ARN of the policy that is used to set the permissions boundary for the user. Always empty.
как вариант, to limit permissions for the user

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user.html.markdown
> +* `path` - Path in which to create the user. Always `""`.
The path for the user name.
в других местах тж поменять

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +* `id` - Unique ID generated by Terraform with the `terraform-` prefix.
Terraform-generated unique ID with ...

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +IAM user group memberships can be imported using the `user`, optionally `project`, and `group_arns` separated by a hash sign (`#`).
the не нужно
\`project\` (optionally), (если только к проекту относится)
либо, если опционально относится и к project and, и к group_arns
"IAM user group memberships can be imported using user, and, optionally, project and group_arns."

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +* `project` - (Optional) The name of the project, which is specified when the user is added to project groups.
The name of the project. Specified when the user is added to project groups.

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_policy_attachment.markdown
> +* `project` - (Optional) The name of the project, which is specified when a project policy is attached.
The name of the project. Specified when a project policy is attached.

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +~> If user isn't a member of some of the specified groups, these groups will be ignored during import.
If the user

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +In addition to all arguments above, the following attributes are exported:
the

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +~> All groups in the `group_arns` must be of the same type: **global** or **project**.
the не надо

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +If groups have a **project** type, `project` must be specified.
a -> the

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_policy_attachment.markdown
> +In addition to all arguments above, the following attributes are exported:
the

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_policy_attachment.markdown
> +* `id` - The `user`, optionally `project`, and `policy_arn` separated by a hash sign (`#`).
the не нужно
`project` (optionally), (если только к проекту относится)

2024-10-07 09:41 UTC, DiGa66 commented on website/docs/r/iam_user_policy_attachment.markdown
> +IAM user policy attachments can be imported using the `id`, e.g.,
the не нужно

2024-10-09 09:11 UTC, PixarV commented on website/docs/d/iam_policy.html.markdown
> +In addition to all arguments above, the following attributes are exported:
Решили пока оставить формулировку с all, тк она используется во всех остальных разделах, и завести задачу на ее обновление сразу везде

2024-10-09 10:24 UTC, PixarV commented on website/docs/r/iam_group_policy_attachment.markdown
> +IAM group policy attachments can be imported using the `id`, e.g.,
Здесь "group policy attachment" получается из имени terraform ресурса (aws_iam_group_policy_attachment), который предлагается импортировать. 

Нужно заменить множественное число на единственное

2024-10-09 10:27 UTC, PixarV commented on website/docs/r/iam_policy.html.markdown
> +* `name` - (Optional, Conflicts with `name_prefix`) The name of the policy. The value can only contain Latin letters, numbers, underscores (_),
Это задается на уровне схемы ресурса в terraform провайдере. Это ограничение говорит о том, что параметры `name` и `name_prefix` не могут быть указаны одновременно

2024-10-09 13:41 UTC, PixarV commented on internal/service/iam/group_membership.go
> +			"group_arn": {
Добавить валидацию `verify.ValidARN` для полей, которые принимаю arn

2024-10-09 13:45 UTC, PixarV commented on internal/service/iam/project.go
> +		if d.HasChange("display_name") {
if лишний

2024-10-11 09:35 UTC, PixarV commented on internal/service/iam/group.go
> +	d.Set("group_id", group.GroupId)
Поднять выше

2024-10-11 09:35 UTC, PixarV commented on internal/service/iam/group.go
> +	group, _, err := FindGroupByArn(conn, arn)
Имя все таки можно безопасно взять из схемы

2024-10-11 09:36 UTC, PixarV commented on internal/service/iam/policy.go
> +		policy, err := FindPolicyByArn(conn, arn)
Имя все таки можно безопасно взять из схемы

2024-10-11 09:36 UTC, PixarV commented on internal/service/iam/policy.go
> +	policy, err := FindPolicyByArn(conn, arn)
Имя все таки можно безопасно взять из схемы

2024-10-11 09:37 UTC, PixarV commented on internal/service/iam/user_data_source.go
>  	d.Set("user_id", user.UserId)
Поднять выше

2024-10-11 10:17 UTC, PixarV commented on website/docs/d/iam_group.html.markdown
> +~> Filtering by `name` is done locally and could have a performance impact if the list of groups is large.
Поправила

2024-10-11 10:26 UTC, PixarV commented on website/docs/r/iam_group.html.markdown
> +* `path` - Path in which to create the group. Always `""`.
Взяла более понятную версию `The path to the group.` из описания [Group Data Type от AWS](https://docs.aws.amazon.com/IAM/latest/APIReference/API_Group.html).

2024-10-11 10:28 UTC, PixarV commented on website/docs/r/iam_group_membership.html.markdown
> +To manage a specific user in multiple groups,
Также поправила для iam_user_group_membership.

2024-10-11 10:54 UTC, PixarV commented on website/docs/r/iam_user.html.markdown
> +* `permissions_boundary` - The ARN of the policy that is used to set the permissions boundary for the user. Always empty.
Поправила и тут, и в датасорсе

2024-10-11 10:56 UTC, PixarV commented on website/docs/r/iam_user.html.markdown
> +* `path` - Path in which to create the user. Always `""`.
Взяла более понятную версию `The path to the user.` из описания [User Data Type от AWS](https://docs.aws.amazon.com/IAM/latest/APIReference/API_User.html)

Для датасорса тоже поменяла

2024-10-11 10:58 UTC, PixarV commented on website/docs/r/iam_user_group_membership.html.markdown
> +IAM user group memberships can be imported using the `user`, optionally `project`, and `group_arns` separated by a hash sign (`#`).
Использую вариант `project` (optionally)

2024-10-11 12:16 UTC, PixarV commented on website/docs/r/iam_group.html.markdown
> +In addition to all arguments above, the following attributes are exported:
см. [коммент](https://github.com/C2Devel/terraform-provider-rockitcloud/pull/55#discussion_r1793161129)

2024-10-11 12:17 UTC, PixarV commented on website/docs/r/iam_group_membership.html.markdown
> +In addition to all arguments above, the following attributes are exported:
см. [коммент](https://github.com/C2Devel/terraform-provider-rockitcloud/pull/55#discussion_r1793161129)

2024-10-11 12:17 UTC, PixarV commented on website/docs/r/iam_policy.html.markdown
> +In addition to all arguments above, the following attributes are exported:
см. [коммент](https://github.com/C2Devel/terraform-provider-rockitcloud/pull/55#discussion_r1793161129)

2024-10-11 12:17 UTC, PixarV commented on website/docs/r/iam_user_group_membership.html.markdown
> +In addition to all arguments above, the following attributes are exported:
см. [коммент](https://github.com/C2Devel/terraform-provider-rockitcloud/pull/55#discussion_r1793161129)

2024-10-11 12:17 UTC, PixarV commented on website/docs/r/iam_user_policy_attachment.markdown
> +In addition to all arguments above, the following attributes are exported:
см. [коммент](https://github.com/C2Devel/terraform-provider-rockitcloud/pull/55#discussion_r1793161129)

2024-10-14 10:28 UTC, DiGa66 requested changes

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/d/iam_group.html.markdown
> +* `arn` - The ARN of the user.
Как понимаю, это пользователь в группе, и их может быть быть несколько (раздел называется users).
Соответственно, a user

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/d/iam_group.html.markdown
> +* `user_id` - The ID of the user.
a user

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/d/iam_group.html.markdown
> +* `user_name` - The name of the user.
a user

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/d/iam_group.html.markdown
> +    * `path` - The path to the user. Always `""`.
a user

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/d/iam_policy.html.markdown
> +* `tags` - Key-value mapping of tags for the IAM Policy. Always empty.
policy со строчной (см. предыдущую строку

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/d/iam_user.html.markdown
> +* `path` - The path to the user. Always `""`.
На подумать. А надо ли неподдерживаемые атрибуты описывать? Может только значение оставлять. Зачем грузить ненужной информацией.

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/d/iam_users.html.markdown
> +* `names` - List of names of the users.
List of user names.

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/r/iam_group_membership.html.markdown
> +* `users` - (Required) List of names of the users.
List of user names.

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/d/iam_users.html.markdown
> +Provides ARNs (Amazon Resource Names) and names of selected IAM users.
the names

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/r/iam_group.html.markdown
> +Manually managing user/group membership via the cloud console alongside using
поскольку "or", то the ... or ... resource (арт. + ед. ч.)

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/r/iam_group_policy_attachment.markdown
> +  Attaches an IAM Policy to an IAM group.
policy (поменять по всем текстам на строчную)

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/r/iam_policy.html.markdown
> +* `name` - (Optional, Conflicts with `name_prefix`) The name of the policy. The value can only contain Latin letters, numbers, underscores (_),
я имел ввиду саму формулировку

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/r/iam_user.html.markdown
> +~> Usernames are not case-sensitive. For example, you cannot create users named "TESTUSER" and "testuser" at the same time.
users named -> user names (в других местах тж поменять)

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +* import user global groups membership:
group membership

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +* import user project groups membership for project `project-example`:
group membership

2024-10-14 10:28 UTC, DiGa66 commented on website/docs/r/iam_user_group_membership.html.markdown
> +If groups have the **project** type, `project` must be specified.
If groups are of the ...

2024-10-14 11:03 UTC, PixarV commented on website/docs/d/iam_user.html.markdown
> +* `path` - The path to the user. Always `""`.
Я оставляла описание, чтобы было немного больше контекста у таких параметров. Возможно у кого-то появился бы запрос на добавление функциональности ) 

Заведу задачу на подумать.

2024-10-14 11:18 UTC, PixarV commented on website/docs/r/iam_policy.html.markdown
> +* `name` - (Optional, Conflicts with `name_prefix`) The name of the policy. The value can only contain Latin letters, numbers, underscores (_),
Ее используют при описании ресурсов в aws провайдере. Иногда размещают в конце описания: 
```
name_prefix - (Optional, Forces new resource) Creates a unique name beginning with the specified prefix. Conflicts with name.
```
Вариант, который я тут решила использовать, тоже у них подсмотрела. Мне он нравится больше, тк это важное ограничение, которое можно не увидеть из-за длинного описания

2024-10-17 08:14 UTC, PixarV commented on website/docs/d/iam_group.html.markdown
> +* `arn` - The ARN of the user.
Да, все так. Заменила артикль тут и ниже

2024-10-17 08:24 UTC, PixarV commented on website/docs/r/iam_user.html.markdown
> +~> Usernames are not case-sensitive. For example, you cannot create users named "TESTUSER" and "testuser" at the same time.
Заменила еще в первом предложении тут Username -> User names. Получилось так:
```
~> User names are not case-sensitive. For example, you cannot create user names "TESTUSER" and "testuser" at the same time.
```

2024-10-17 18:15 UTC, No-Rib approved these changes

2024-10-25 11:18 UTC, vamping111 commented on website/docs/r/iam_group_policy_attachment.markdown
> +$ terraform import aws_iam_group_policy_attachment.example arn:c2:iam::test.customer:group/group-example#arn:c2:iam:::policy/BackupFullAccess
Скорее всего строка импорта должна быть следующей:

$ terraform import aws_iam_group_policy_attachment.example arn:c2:iam::test.customer:group/group-example#arn:c2:iam::test.customer:policy/BackupFullAccess

2024-10-25 12:48 UTC, PixarV commented on website/docs/r/iam_group_policy_attachment.markdown
> +$ terraform import aws_iam_group_policy_attachment.example arn:c2:iam::test.customer:group/group-example#arn:c2:iam:::policy/BackupFullAccess
Эта политика, которую предоставляет облако. В ее арне не указывается заказчик

2024-11-05 16:03 UTC, DiGa66 approved these changes

2024-11-05 16:38 UTC, merged