add direct connect support
C2Devel/terraform-provider-croccloud pull request #66
Opened 2024-11-22 16:40 UTC by nktrnv

FEATURES:
- **New Data Source:** `aws_dx_connection`
- **New Data Source:** `aws_dx_gateway`
- **New Data Source:** `aws_dx_lag`
- **New Data Source:** `aws_ec2_transit_gateway`
- **New Resource:** `aws_dx_gateway`
- **New Resource:** `aws_dx_gateway_association`
- **New Resource:** `aws_dx_transit_virtual_interface`

2024-12-01 10:37 UTC, cactusFriday commented on website/docs/d/dx_lag.html.markdown
> +* `location` - The physical site to which the LAG is connected.
у Connection немного другая формулировка

2024-12-01 10:37 UTC, cactusFriday commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +  name            = "tf-dxg-example"
tg-dxgw наверное

2024-12-01 10:37 UTC, cactusFriday commented on website/docs/r/dx_transit_virtual_interface.html.markdown
>    name            = "tf-dxg-example"
tf-dxgw

2024-12-01 10:37 UTC, cactusFriday commented on website/docs/d/dx_lag.html.markdown
> +## Attributes Reference
а мы не добавляем available_vlans? Или сюда это не нужно. У AWS если не ошибаюсь, нет vlans, у них вроде по дефолту весь рендж доступен

2024-12-02 11:00 UTC, nktrnv commented on website/docs/d/dx_lag.html.markdown
> +* `location` - The physical site to which the LAG is connected.
А вообще какие формулировки будут норм? У AWS же там действительно локации и они используют такие:
> The location of the LAG.
> The location of the connection.

У нас там по сути зоны доступности. Стоит ли об этом как-то упомянуть или можно написать более абстрактно, как у AWS? Ну или оставить предложенную мной, только сделать ее одинаковой для конекшена и лага (я кстати взял ее с нашей публичной документации на сервис):
> The physical site of the connection
> The physical site of the LAG

2024-12-02 11:12 UTC, nktrnv commented on website/docs/d/dx_lag.html.markdown
> +## Attributes Reference
Насколько я понимаю не нужно, так как его будет проблематично поддерживать. @PixarV, посмотри, пожалуйста

2024-12-02 15:50 UTC, DiGa66 requested changes

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/dx_connection.html.markdown
> +* `location` - The physical site of the connection.
либо как в AWS -- The location of the connection.
либо -- The physical site, where the connection terminates.

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/dx_connection.html.markdown
> +* `owner_account_id` - The ID of the project that owns the connection.
project? в AWS это account

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/dx_connection.html.markdown
> +* `tags` - A map of tags for the resource.
у нас нет такого понятия, как карта тегов. Лучше
The tags assigned to the resource.

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/dx_gateway.html.markdown
> +* `amazon_side_asn` - The ASN configured on the cloud side of the connection.
The ASN for the cloud side of the connection

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/dx_gateway.html.markdown
> +* `owner_account_id` - The ID of the project that owns the Direct Connect gateway.
account?

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/dx_lag.html.markdown
> +* `location` - The physical site to which the LAG is connected.
тогда уж:
The phisycal site where the connection terminates.
(у AWS тоже не совсем корректная формулировка, скорее уж
_The location of an endpoint of the connection_
Ну и мы не обязаны ей следовать)

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/dx_lag.html.markdown
> +* `owner_account_id` - The ID of the project that owns the LAG.
account?

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/dx_lag.html.markdown
> +* `tags` - A map of tags for the resource.
The tags assigned to the connection.

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +### By EC2 transit gateway and Direct Connect gateway identifiers
тут не понял, что хотели сказать с помощью By

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +  Provides information on an EC2 transit gateway's attachment to a Direct Connect gateway.
the attachment of an EC2 transit gateway

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +Provides information on an EC2 transit gateway's attachment to a Direct Connect gateway.
the attachment of an EC2 transit gateway 
либо EC2 transit gateway attachment (см. ниже association)

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +* `filter` - (Optional) One or more configuration blocks containing name-values filters. The structure of this block is [described below](#filter-configuration-block).
containing => with
name-value

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +The following arguments are supported by the `filter` configuration block:
a ... block, их же может быть несколько

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +* `name` - (Required) The name of the filter field. Valid values can be found in the [EC2 DescribeTransitGatewayAttachments API Reference][describe-transit-gateway-attachments].
после in артикль можно опустить
может просто filter, field выглядит как буквальный перевод

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +* `tags` - Key-value tags for the EC2 transit gateway attachment.
Key-value кажется здесь лишним
для единообразия можно использовать формулировку как выше

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_gateway.html.markdown
> +* `owner_account_id` - The ID of the project that owns the Direct Connect gateway.
account?

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_gateway_association.html.markdown
> +* `dx_gateway_owner_account_id` - The ID of the project that owns the Direct Connect gateway.
account ?

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_gateway_association.html.markdown
> +* `associated_gateway_owner_account_id` - The ID of the account that owns the VGW or transit gateway with which to associate the Direct Connect gateway.
project ?
VGW здесь ниоткуда появляется...
that the Direct Connect gateway must be associated with

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_gateway_association.html.markdown
> +  Manages a Direct Connect gateway association with a transit gateway.
or VGW ?
так у амазон и ниже VGW упоминается

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_gateway_association.html.markdown
> +* `associated_gateway_id` - (Required) The ID of the transit gateway with which to associate the Direct Connect gateway.
The ID of the transit gateway that the Direct Connection gateway must be associated with.

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_gateway_association.html.markdown
> +* `id` - The ID of the Direct Connect gateway association resource.
Это что за зверь? Если id ассоциации, а есть id ресурса ассоциации?
а ниже id предложения ассоциации. Это что-то третье?

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +  Manages a Direct Connect transit virtual interface.
Транзитный виртуальные интерфейс?
В пользовательской доке есть только виртуальный интерфейс

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +Manages a Direct Connect transit virtual interface.
transit ?

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `tags` - (Optional) A map of tags to assign to the resource. If configured with a provider [`default_tags` configuration block][default-tags] present, tags with matching keys will overwrite those d
Tags assigned to the resource
Не очень понятна фраза с If: configured выглядит как лишнее
возможно имелось ввиду If there is a provider [`default_tags` configuration block][default-tags],
provider level

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `tags_all` - A map of tags assigned to the resource, including those inherited from the provider [`default_tags` configuration block][default-tags].
Tags assigned to the resource, ...

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `mtu` - The maximum transmission unit (MTU) is the size, in bytes, of the largest permissible packet that can be passed over the connection. Always `0`.
passed -> transferred

2024-12-02 15:50 UTC, DiGa66 commented on website/docs/r/dx_gateway_association.html.markdown
> +- `create` - (Default `30 minutes`) Used for creating the association
м.б. Used заменить здесь и в других местах на Timeout ?

2024-12-02 17:19 UTC, cactusFriday commented on website/docs/r/dx_gateway_association.html.markdown
> +  Manages a Direct Connect gateway association with a transit gateway.
так, наверное, намеренно сделано. У нас ассоциация возможна только между DCGW и TGW.

2024-12-03 14:18 UTC, nktrnv commented on website/docs/d/dx_connection.html.markdown
> +* `tags` - A map of tags for the resource.
В данном случае имеется в виду один из типов данных [map](https://developer.hashicorp.com/terraform/language/expressions/types#map) терраформа, такая формулировка у нас используется по всей доке. Можем убрать

2024-12-03 14:27 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +### By EC2 transit gateway and Direct Connect gateway identifiers
Attachment можно получить с помощью следующих аргументов: `transit_gateway_id`, `dx_gateway_id`, `filter`. Все они опциональные. С помощью заголовка пояснили, что мы используем в примере `transit_gateway_id` и `dx_gateway_id`

2024-12-03 14:30 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +  Provides information on an EC2 transit gateway's attachment to a Direct Connect gateway.
Не очень понял, что нужно поменять. Так?
```suggestion
  Provides information about the attachment of an EC2 transit gateway to a Direct Connect gateway.
```

2024-12-03 14:33 UTC, nktrnv commented on website/docs/d/dx_connection.html.markdown
> +* `location` - The physical site of the connection.
Поправил

2024-12-03 14:35 UTC, nktrnv commented on website/docs/d/dx_gateway.html.markdown
> +* `amazon_side_asn` - The ASN configured on the cloud side of the connection.
Поправил

2024-12-03 14:36 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +* `filter` - (Optional) One or more configuration blocks containing name-values filters. The structure of this block is [described below](#filter-configuration-block).
Поправил

2024-12-03 14:40 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +* `name` - (Required) The name of the filter field. Valid values can be found in the [EC2 DescribeTransitGatewayAttachments API Reference][describe-transit-gateway-attachments].
Поправил

2024-12-03 14:42 UTC, nktrnv commented on website/docs/d/dx_lag.html.markdown
> +* `tags` - A map of tags for the resource.
Поправил

2024-12-03 14:44 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +* `tags` - Key-value tags for the EC2 transit gateway attachment.
Поправил

2024-12-03 14:46 UTC, nktrnv commented on website/docs/r/dx_gateway_association.html.markdown
> +* `associated_gateway_owner_account_id` - The ID of the account that owns the VGW or transit gateway with which to associate the Direct Connect gateway.
Это же неподдерживаемые параметры

2024-12-03 14:46 UTC, nktrnv commented on website/docs/r/dx_gateway_association.html.markdown
> +  Manages a Direct Connect gateway association with a transit gateway.
Все верно, у нас VGW нет, поэтому мы это не упоминаем

2024-12-03 14:47 UTC, nktrnv commented on website/docs/r/dx_gateway_association.html.markdown
> +* `associated_gateway_id` - (Required) The ID of the transit gateway with which to associate the Direct Connect gateway.
Это неподдерживаемый параметр, у него точно стоит менять формулировку или лучше оставить как у AWS?

2024-12-03 14:51 UTC, nktrnv commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +  Manages a Direct Connect transit virtual interface.
Это он и есть, так как в Direct Connect у нас поддерживается один тип виртуальных интерфейсов - транзитные

2024-12-03 14:58 UTC, nktrnv commented on website/docs/d/dx_lag.html.markdown
> +* `location` - The physical site to which the LAG is connected.
Поправил

2024-12-03 14:59 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +  name            = "tf-dxg-example"
Поправил

2024-12-03 14:59 UTC, nktrnv commented on website/docs/r/dx_transit_virtual_interface.html.markdown
>    name            = "tf-dxg-example"
Поправил

2024-12-03 15:09 UTC, nktrnv commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `tags` - (Optional) A map of tags to assign to the resource. If configured with a provider [`default_tags` configuration block][default-tags] present, tags with matching keys will overwrite those d
Поправил

2024-12-03 15:11 UTC, nktrnv commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `tags` - (Optional) A map of tags to assign to the resource. If configured with a provider [`default_tags` configuration block][default-tags] present, tags with matching keys will overwrite those d
Почему _Tags assigned to the resource_, а не _Tags to assign to the resource_, теги же еще не присвоены, а будут присвоены при создании ресурса

2024-12-03 15:15 UTC, nktrnv commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `tags_all` - A map of tags assigned to the resource, including those inherited from the provider [`default_tags` configuration block][default-tags].
Поправил

2024-12-03 16:48 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +The following arguments are supported by the `filter` configuration block:
Поправил

2024-12-03 16:49 UTC, nktrnv commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `mtu` - The maximum transmission unit (MTU) is the size, in bytes, of the largest permissible packet that can be passed over the connection. Always `0`.
Это неподдерживаемый параметр, у него точно стоит менять формулировку или лучше оставить как у AWS?

2024-12-03 16:51 UTC, nktrnv commented on website/docs/r/dx_gateway_association.html.markdown
> +- `create` - (Default `30 minutes`) Used for creating the association
Я не против, поправил

2024-12-03 18:50 UTC, nktrnv commented on website/docs/d/dx_connection.html.markdown
> +* `owner_account_id` - The ID of the project that owns the connection.
Поправил

2024-12-03 18:50 UTC, nktrnv commented on website/docs/d/dx_gateway.html.markdown
> +* `owner_account_id` - The ID of the project that owns the Direct Connect gateway.
Поправил

2024-12-03 18:50 UTC, nktrnv commented on website/docs/d/dx_lag.html.markdown
> +* `owner_account_id` - The ID of the project that owns the LAG.
Поправил

2024-12-03 18:51 UTC, nktrnv commented on website/docs/r/dx_gateway.html.markdown
> +* `owner_account_id` - The ID of the project that owns the Direct Connect gateway.
Поправил

2024-12-03 18:51 UTC, nktrnv commented on website/docs/r/dx_gateway_association.html.markdown
> +* `dx_gateway_owner_account_id` - The ID of the project that owns the Direct Connect gateway.
Поправил

2024-12-03 18:51 UTC, nktrnv commented on website/docs/r/dx_gateway_association.html.markdown
> +* `id` - The ID of the Direct Connect gateway association resource.
Поправил, теперь `dx_gateway_association_id` нет, только `id`

2024-12-04 08:58 UTC, nktrnv commented on website/docs/d/dx_connection.html.markdown
> +* `owner_account_id` - The ID of the project that owns the connection.
UPD: решили оставить как есть

2024-12-04 08:58 UTC, nktrnv commented on website/docs/d/dx_gateway.html.markdown
> +* `owner_account_id` - The ID of the project that owns the Direct Connect gateway.
UPD: решили оставить как есть

2024-12-04 08:58 UTC, nktrnv commented on website/docs/d/dx_lag.html.markdown
> +* `owner_account_id` - The ID of the project that owns the LAG.
UPD: решили оставить как есть

2024-12-04 08:58 UTC, nktrnv commented on website/docs/r/dx_gateway.html.markdown
> +* `owner_account_id` - The ID of the project that owns the Direct Connect gateway.
UPD: решили оставить как есть

2024-12-04 08:59 UTC, nktrnv commented on website/docs/r/dx_gateway_association.html.markdown
> +* `dx_gateway_owner_account_id` - The ID of the project that owns the Direct Connect gateway.
UPD: решили оставить как есть

2024-12-04 12:10 UTC, cactusFriday approved these changes

2024-12-04 12:10 UTC, cactusFriday commented on internal/service/directconnect/gateway_association.go
>  			"vpn_gateway_id": {
а мы не хотим дропнуть этот параметр? Тут уже написано, что он депрекейтед, в API мы такой параметр не будем поддерживать.

2024-12-04 12:10 UTC, cactusFriday commented on website/docs/r/dx_gateway_association.html.markdown
> +* `associated_gateway_id` - (Required) The ID of the transit gateway with which to associate the Direct Connect gateway.
почему неподдерживаемый? Это ведь как раз единственный поддерживаемый

2024-12-04 12:15 UTC, nktrnv commented on website/docs/r/dx_gateway_association.html.markdown
> +* `associated_gateway_id` - (Required) The ID of the transit gateway with which to associate the Direct Connect gateway.
Промахнулся комментом)
Поправил

2024-12-11 13:06 UTC, DiGa66 requested changes

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/d/dx_lag.html.markdown
> +* `bandwidth` - The individual bandwidth of the physical connections bundled by the LAG.
тут число не согласуется. Насколько помню, в LAG у всех соединений bandwidth одинакова. Тогда так:

The bandwidth of each physical connection in the LAG.

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/d/dx_lag.html.markdown
> +* `location` - The physical site to which the LAG is connected.
тут вроде без изменений

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +  Provides information on an EC2 transit gateway's attachment to a Direct Connect gateway.
да, так. Можно оставить предлог "on"

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +### By EC2 transit gateway and Direct Connect gateway identifiers
тут тогда лучше описательно:

 Using EC2 transit gateway and Direct Connect gateway identifiers to get information on the attachment

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +* `filter` - (Optional) One or more configuration blocks with name-value filters. The structure of this block is [described below](#filter-configuration-block).
The structure of a block
( this означает конкретный (этот) блок)

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +* `values` - (Required) Set of values that are accepted for the given filter field. Results will be selected if any given value matches.
Set of valid values for a given filter field.
matches -- тут по грамматике нужно, с чем совпадает (чему соответствует)

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/r/dx_gateway.html.markdown
> +Direct Connect gateways can be imported using the `id`, e.g.,
the не нужно здсь

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/r/dx_gateway_association.html.markdown
> +* `associated_gateway_owner_account_id` - The ID of the account that owns the VGW or transit gateway with which to associate the Direct Connect gateway.
поправить как выше:
that the Direct Connection gateway must be associated with

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `dx_gateway_id` - (Required) The ID of the Direct Connect gateway to which to connect the virtual interface.
that the virtual interface must be connected to

2024-12-11 13:06 UTC, DiGa66 commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `connection_id` - (Required) The ID of the Direct Connect connection (or LAG) on which to create the virtual interface.
on which the virtual interface has to be created

2024-12-17 09:06 UTC, nktrnv commented on website/docs/d/dx_lag.html.markdown
> +* `bandwidth` - The individual bandwidth of the physical connections bundled by the LAG.
Поправил

2024-12-17 09:11 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +  Provides information on an EC2 transit gateway's attachment to a Direct Connect gateway.
Поправил

2024-12-17 09:11 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +Provides information on an EC2 transit gateway's attachment to a Direct Connect gateway.
Поправил

2024-12-17 09:14 UTC, nktrnv commented on website/docs/d/ec2_transit_gateway_dx_gateway_attachment.html.markdown
> +* `filter` - (Optional) One or more configuration blocks with name-value filters. The structure of this block is [described below](#filter-configuration-block).
Поправил

2024-12-17 09:15 UTC, nktrnv commented on website/docs/r/dx_gateway.html.markdown
> +Direct Connect gateways can be imported using the `id`, e.g.,
Поправил

2024-12-17 09:18 UTC, nktrnv commented on website/docs/r/dx_gateway_association.html.markdown
> +* `associated_gateway_owner_account_id` - The ID of the account that owns the VGW or transit gateway with which to associate the Direct Connect gateway.
Unsupported attributes предлагаю оставить как есть

2024-12-17 09:19 UTC, nktrnv commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `dx_gateway_id` - (Required) The ID of the Direct Connect gateway to which to connect the virtual interface.
Поправил

2024-12-17 09:20 UTC, nktrnv commented on website/docs/r/dx_transit_virtual_interface.html.markdown
> +* `connection_id` - (Required) The ID of the Direct Connect connection (or LAG) on which to create the virtual interface.
Поправил

2024-12-17 09:40 UTC, nktrnv commented on website/docs/d/dx_lag.html.markdown
> +* `location` - The physical site to which the LAG is connected.
Поправил и для LAG: сделал такую же формулировку, как у connection

2024-12-20 07:52 UTC, DiGa66 approved these changes

2024-12-20 07:52 UTC, DiGa66 commented on website/docs/r/dx_gateway_association.md
> +* `associated_gateway_owner_account_id` - The ID of the account that owns the VGW or transit gateway with which to associate the Direct Connect gateway.
with which the Direct Connect gateway has to be associated

2024-12-20 07:55 UTC, merged

2024-12-20 07:55 UTC, nktrnv commented on website/docs/r/dx_gateway_association.md
> +* `associated_gateway_owner_account_id` - The ID of the account that owns the VGW or transit gateway with which to associate the Direct Connect gateway.
Unsupported attributes предлагаю не менять