support legacyClusterParams.masterConfig block for EKS clusters
C2Devel/terraform-provider-croccloud pull request #69
Opened 2024-11-29 14:27 UTC by PixarV

2024-12-02 16:05 UTC, DiGa66 requested changes

2024-12-02 16:05 UTC, DiGa66 commented on website/docs/d/eks_cluster.html.markdown
> +    * `master_config` - The configuration of the cluster master node.
of the master node of the cluster.

2024-12-02 16:05 UTC, DiGa66 commented on website/docs/d/eks_cluster.html.markdown
> +        * `volume_iops` - The number of read/write operations per second of the master node volume.
for the master node volume

2024-12-02 16:05 UTC, DiGa66 commented on website/docs/r/eks_cluster.html.markdown
> +By default, EKS clusters created by Terraform are [high availability clusters][ha-clusters].
By default, Terraform creates [high availability clusters][ha-clusters].

2024-12-02 16:05 UTC, DiGa66 commented on website/docs/r/eks_cluster.html.markdown
> +This example uses the VPC and subnet defined in the [EKS HA Cluster example](#eks-ha-cluster).
This example uses the same VPC and subnet as in [EKS HA Cluster example](#eks-ha-cluster).
надо где-то расшифровку HA дать или использовать полны термин

2024-12-02 16:05 UTC, DiGa66 commented on website/docs/r/eks_cluster.html.markdown
> +* `volume_iops` - (Optional) The number of read/write operations per second of the master node volume.
for the master node volume

2024-12-02 16:05 UTC, DiGa66 commented on website/docs/r/eks_cluster.html.markdown
> +* `master_config` – (Optional) The configuration of the cluster master node.
of the master node of the cluster

2024-12-05 13:12 UTC, astroline approved these changes

2024-12-11 08:55 UTC, PixarV commented on website/docs/r/eks_cluster.html.markdown
> +This example uses the VPC and subnet defined in the [EKS HA Cluster example](#eks-ha-cluster).
Формулировку поправила
Заменила аббревиатуру на полный термин в заголовках примеров

2024-12-11 12:03 UTC, DiGa66 approved these changes

2024-12-19 15:41 UTC, merged